import { Lesson } from '@/types'

// A1 Lessons: Body, Clothes, House (Lessons 71-85)
export const a1LessonsBodyClothesHouse: Lesson[] = [
  // ==================== ТЕЛО, ОДЕЖДА, ДОМ (15 УРОКОВ) ====================
  {
    id: 'a1-71',
    levelId: 'a1',
    title: 'Части тела: Голова',
    description: 'La cabeza y la cara',
    content: {
      introduction: {
        title: 'Partes del cuerpo: La cabeza',
        goals: [
          'Выучить части головы и лица',
          'Научиться описывать внешность',
          'Использовать при визите к врачу',
          'Говорить о боли (Me duele...)',
        ],
        overview: 'Части тела нужно знать для описания внешности и общения с врачом.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: La cabeza',
        explanation: 'Части головы и конструкция Me duele',
        examples: [
          { spanish: 'La cabeza', russian: 'голова' },
          { spanish: 'El pelo / El cabello', russian: 'волосы' },
          { spanish: 'Los ojos', russian: 'глаза' },
          { spanish: 'La nariz', russian: 'нос' },
          { spanish: 'La boca', russian: 'рот' },
          { spanish: 'Las orejas', russian: 'уши' },
          { spanish: 'Los dientes', russian: 'зубы' },
          { spanish: 'Me duele la cabeza', russian: 'у меня болит голова' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-71.mp3',
        transcript: 'Tengo el pelo largo y negro. Mis ojos son marrones. Mi nariz es pequeña. Tengo dolor de cabeza hoy. Me duelen los dientes - necesito ir al dentista. Las orejas son importantes para escuchar.',
        questions: [
          {
            question: '¿Cómo es el pelo de la persona?',
            options: ['corto y rubio', 'largo y negro', 'corto y negro', 'largo y rubio'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué le duele?',
            options: ['la cabeza y los dientes', 'solo la cabeza', 'solo los dientes', 'las orejas'],
            correctAnswer: 0,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Tengo los ojos azules',
          russian: 'У меня голубые глаза',
          context: 'Описание внешности',
        },
        {
          spanish: 'Me duele mucho la cabeza',
          russian: 'У меня сильно болит голова',
          context: 'У врача',
        },
        {
          spanish: 'Tiene el pelo rubio',
          russian: 'У него/неё светлые волосы',
          context: 'Описание другого человека',
        },
      ],
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-71.mp3',
    readingText: 'Para describir a alguien, hablamos de LA CABEZA. EL PELO puede ser: largo/corto, rubio/moreno/negro/pelirrojo, liso/rizado. LOS OJOS: azules, verdes, marrones, negros. LA NARIZ: grande, pequeña, respingona. LA BOCA y LOS DIENTES son importantes. LAS OREJAS sirven para escuchar. Para expresar dolor: Me duele la cabeza (у меня болит голова).',
    duration: 28,
    order: 71,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-72',
    levelId: 'a1',
    title: 'Части тела: Туловище и конечности',
    description: 'El cuerpo, brazos y piernas',
    content: {
      introduction: {
        title: 'El cuerpo y las extremidades',
        goals: [
          'Выучить части тела',
          'Научиться говорить о движениях',
          'Использовать при занятиях спортом',
          'Описывать боль и травмы',
        ],
        overview: 'Основные части тела для повседневного общения и описания действий.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: El cuerpo',
        explanation: 'Туловище и конечности',
        examples: [
          { spanish: 'El cuello', russian: 'шея' },
          { spanish: 'Los hombros', russian: 'плечи' },
          { spanish: 'Los brazos', russian: 'руки (от плеча)' },
          { spanish: 'Las manos', russian: 'руки (кисти)' },
          { spanish: 'Los dedos', russian: 'пальцы' },
          { spanish: 'El pecho / El torso', russian: 'грудь/торс' },
          { spanish: 'Las piernas', russian: 'ноги' },
          { spanish: 'Los pies', russian: 'ступни' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-72.mp3',
        transcript: 'En el gimnasio ejercito todo el cuerpo. Levanto los brazos, muevo las piernas. Me duelen los hombros después del entrenamiento. Los dedos de las manos son diez. También tengo diez dedos en los pies. Las piernas son fuertes.',
        questions: [
          {
            question: '¿Qué le duele después del entrenamiento?',
            options: ['los brazos', 'los hombros', 'las piernas', 'los pies'],
            correctAnswer: 1,
          },
          {
            question: '¿Cuántos dedos tiene en las manos?',
            options: ['cinco', 'ocho', 'diez', 'veinte'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Levanta los brazos',
          russian: 'Подними руки',
          context: 'Инструкция/команда',
        },
        {
          spanish: 'Me rompí la pierna',
          russian: 'Я сломал ногу',
          context: 'О травме',
        },
        {
          spanish: 'Dame la mano',
          russian: 'Дай мне руку',
          context: 'Просьба',
        },
      ],
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: false,
      },
    },
    audioUrl: '/audio/a1-72.mp3',
    readingText: 'El CUERPO humano tiene muchas partes. El CUELLO conecta la cabeza con el cuerpo. Los HOMBROS están arriba. Los BRAZOS terminan en las MANOS. Cada MANO tiene cinco DEDOS. El PECHO o TORSO es el centro. Las PIERNAS son para caminar. Los PIES sostienen el cuerpo. Cada pie tiene cinco dedos también. Para ejercicios: mover los brazos, doblar las piernas.',
    duration: 27,
    order: 72,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-73',
    levelId: 'a1',
    title: 'Одежда: Верхняя одежда',
    description: 'Camisas, pantalones, vestidos',
    content: {
      introduction: {
        title: 'La ropa: Prendas básicas',
        goals: [
          'Выучить основные предметы одежды',
          'Научиться говорить о том, что носим',
          'Использовать глагол LLEVAR (носить)',
          'Делать покупки одежды',
        ],
        overview: 'Основная лексика одежды для повседневного общения и шопинга.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: La ropa',
        explanation: 'Llevar = носить одежду',
        examples: [
          { spanish: 'La camisa', russian: 'рубашка' },
          { spanish: 'La camiseta', russian: 'футболка' },
          { spanish: 'Los pantalones', russian: 'брюки' },
          { spanish: 'Los vaqueros / Los jeans', russian: 'джинсы' },
          { spanish: 'El vestido', russian: 'платье' },
          { spanish: 'La falda', russian: 'юбка' },
          { spanish: 'Llevo una camisa blanca', russian: 'я ношу белую рубашку' },
          { spanish: 'Llevas unos vaqueros azules', russian: 'ты носишь синие джинсы' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-73.mp3',
        transcript: 'Hoy llevo una camiseta negra y unos vaqueros azules. Mi hermana lleva un vestido rojo muy bonito. Para trabajar, llevo camisa y pantalones formales. En verano prefiero ropa ligera. Los vaqueros son muy cómodos.',
        questions: [
          {
            question: '¿Qué lleva la persona hoy?',
            options: ['camisa blanca', 'camiseta negra y vaqueros', 'vestido', 'ropa formal'],
            correctAnswer: 1,
          },
          {
            question: '¿De qué color es el vestido de la hermana?',
            options: ['negro', 'azul', 'rojo', 'blanco'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Qué llevas puesto?',
          russian: 'Что на тебе надето?',
          context: 'Вопрос об одежде',
        },
        {
          spanish: 'Necesito comprar pantalones nuevos',
          russian: 'Мне нужно купить новые брюки',
          context: 'О покупках',
        },
        {
          spanish: 'Este vestido me queda bien',
          russian: 'Это платье мне подходит',
          context: 'Примерка',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-73.mp3',
    readingText: 'La ROPA es esencial. Para el torso: CAMISA (рубашка formal), CAMISETA (футболка casual). Para las piernas: PANTALONES (брюки), VAQUEROS o JEANS (джинсы). Para mujeres: VESTIDO (платье completo), FALDA (юбка). El verbo LLEVAR significa "носить": Llevo una camisa. Ella lleva un vestido. Para compras: "¿Tiene esta camisa en talla M?"',
    duration: 29,
    order: 73,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-74',
    levelId: 'a1',
    title: 'Одежда: Обувь и аксессуары',
    description: 'Zapatos, bolsos, complementos',
    content: {
      introduction: {
        title: 'Calzado y accesorios',
        goals: [
          'Выучить названия обуви',
          'Выучить аксессуары',
          'Научиться спрашивать размер',
          'Использовать в магазине',
        ],
        overview: 'Обувь и аксессуары завершают наряд. Учим как о них говорить.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Calzado y accesorios',
        explanation: 'Обувь и дополнения к одежде',
        examples: [
          { spanish: 'Los zapatos', russian: 'туфли/ботинки' },
          { spanish: 'Las zapatillas / Los tenis', russian: 'кроссовки' },
          { spanish: 'Las botas', russian: 'сапоги' },
          { spanish: 'Las sandalias', russian: 'сандалии' },
          { spanish: 'El bolso / La bolsa', russian: 'сумка' },
          { spanish: 'El cinturón', russian: 'ремень' },
          { spanish: 'El sombrero / La gorra', russian: 'шляпа / кепка' },
          { spanish: '¿Qué número calzas?', russian: 'какой у тебя размер обуви?' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-74.mp3',
        transcript: 'Necesito comprar zapatos nuevos. Calzo el número 42. También quiero unas zapatillas deportivas. Mi madre lleva siempre un bolso grande. En verano uso sandalias. En invierno prefiero botas. Un cinturón negro combina con todo.',
        questions: [
          {
            question: '¿Qué número calza la persona?',
            options: ['40', '41', '42', '43'],
            correctAnswer: 2,
          },
          {
            question: '¿Qué usa en verano?',
            options: ['botas', 'zapatos', 'sandalias', 'zapatillas'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Tienen estos zapatos en mi número?',
          russian: 'У вас есть эти туфли моего размера?',
          context: 'В магазине обуви',
        },
        {
          spanish: 'Me gustan estas zapatillas',
          russian: 'Мне нравятся эти кроссовки',
          context: 'Выбор',
        },
        {
          spanish: 'Llevo gorra para protegerme del sol',
          russian: 'Я ношу кепку, чтобы защититься от солнца',
          context: 'Объяснение',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: false,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-74.mp3',
    readingText: 'El CALZADO es importante. ZAPATOS son formales. ZAPATILLAS o TENIS son deportivas. BOTAS para invierno. SANDALIAS para verano. Pregunta en tienda: "¿Qué número calza?" o "¿Qué talla tiene?". Los ACCESORIOS: BOLSO/BOLSA (сумка), CINTURÓN (ремень), SOMBRERO (шляпа), GORRA (кепка). Estos complementos completan el outfit.',
    duration: 28,
    order: 74,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-75',
    levelId: 'a1',
    title: 'Одежда: Сезонная',
    description: 'Ropa de invierno y verano',
    content: {
      introduction: {
        title: 'Ropa según la estación',
        goals: [
          'Выучить зимнюю одежду',
          'Выучить летнюю одежду',
          'Научиться говорить о погоде и одежде',
          'Использовать глагол PONERSE',
        ],
        overview: 'Разная одежда для разных сезонов и погоды.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Ropa de temporada',
        explanation: 'Ponerse = надевать на себя',
        examples: [
          { spanish: 'El abrigo', russian: 'пальто' },
          { spanish: 'La chaqueta', russian: 'куртка/пиджак' },
          { spanish: 'El jersey / El suéter', russian: 'свитер' },
          { spanish: 'La bufanda', russian: 'шарф' },
          { spanish: 'Los guantes', russian: 'перчатки' },
          { spanish: 'El traje de baño', russian: 'купальник' },
          { spanish: 'Me pongo el abrigo', russian: 'я надеваю пальто' },
          { spanish: 'Hace frío, ponte la chaqueta', russian: 'холодно, надень куртку' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-75.mp3',
        transcript: 'En invierno hace mucho frío. Me pongo el abrigo, la bufanda y los guantes. También llevo un jersey grueso bajo la chaqueta. En verano hace calor. Me pongo ropa ligera y el traje de baño para ir a la playa. Cuando llueve, uso impermeable.',
        questions: [
          {
            question: '¿Qué se pone en invierno?',
            options: ['traje de baño', 'abrigo, bufanda y guantes', 'solo camiseta', 'sandalias'],
            correctAnswer: 1,
          },
          {
            question: '¿Cuándo usa el traje de baño?',
            options: ['en invierno', 'en otoño', 'en verano para la playa', 'cuando llueve'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Hace frío, necesito un abrigo',
          russian: 'Холодно, мне нужно пальто',
          context: 'О погоде и одежде',
        },
        {
          spanish: 'No olvides la bufanda',
          russian: 'Не забудь шарф',
          context: 'Напоминание',
        },
        {
          spanish: 'En verano llevo ropa fresca',
          russian: 'Летом я ношу легкую одежду',
          context: 'О сезонных привычках',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-75.mp3',
    readingText: 'La ropa cambia según la estación. En INVIERNO (hace frío): ABRIGO (пальто), CHAQUETA (куртка), JERSEY/SUÉTER (свитер), BUFANDA (шарф), GUANTES (перчатки). En VERANO (hace calor): ropa ligera, TRAJE DE BAÑO (купальник), shorts, camisetas. El verbo PONERSE = надевать: Me pongo el abrigo. Ponte los guantes. En otoño/primavera: ropa intermedia.',
    duration: 30,
    order: 75,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-76',
    levelId: 'a1',
    title: 'Дом: Комнаты',
    description: 'Las habitaciones de la casa',
    content: {
      introduction: {
        title: 'Las habitaciones',
        goals: [
          'Выучить названия комнат',
          'Научиться описывать свой дом',
          'Говорить о количестве комнат',
          'Использовать HAY и TENER',
        ],
        overview: 'Названия комнат в доме для описания жилья.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Habitaciones',
        explanation: 'Комнаты и фразы "hay" / "tengo"',
        examples: [
          { spanish: 'La sala / El salón', russian: 'гостиная' },
          { spanish: 'El dormitorio / La habitación', russian: 'спальня/комната' },
          { spanish: 'La cocina', russian: 'кухня' },
          { spanish: 'El baño', russian: 'ванная' },
          { spanish: 'El comedor', russian: 'столовая' },
          { spanish: 'Mi casa tiene tres dormitorios', russian: 'в моем доме три спальни' },
          { spanish: 'En mi apartamento hay dos baños', russian: 'в моей квартире две ванные' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-76.mp3',
        transcript: 'Vivo en un apartamento con tres habitaciones. Tenemos una sala grande, una cocina moderna, tres dormitorios y dos baños. El comedor está junto a la cocina. Mi dormitorio es pequeño pero cómodo. El baño principal es espacioso.',
        questions: [
          {
            question: '¿Cuántos dormitorios tiene el apartamento?',
            options: ['dos', 'tres', 'cuatro', 'cinco'],
            correctAnswer: 1,
          },
          {
            question: '¿Cómo es el dormitorio de la persona?',
            options: ['grande', 'pequeño pero cómodo', 'espacioso', 'moderno'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Cuántas habitaciones tiene tu casa?',
          russian: 'Сколько комнат в твоем доме?',
          context: 'Вопрос о жилье',
        },
        {
          spanish: 'Mi casa tiene dos baños',
          russian: 'В моем доме две ванные',
          context: 'Описание дома',
        },
        {
          spanish: 'La cocina es muy grande',
          russian: 'Кухня очень большая',
          context: 'Характеристика',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-76.mp3',
    readingText: 'Las habitaciones principales de una casa: SALA o SALÓN (гостиная) donde recibes visitas. DORMITORIO o HABITACIÓN (спальня) donde duermes. COCINA (кухня) donde cocinas. BAÑO (ванная) para higiene. COMEDOR (столовая) donde comes. Para describir: Mi casa tiene X dormitorios. En mi apartamento hay X baños. Grande, pequeño, cómodo, moderno son adjetivos útiles.',
    duration: 29,
    order: 76,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-77',
    levelId: 'a1',
    title: 'Дом: Мебель гостиной',
    description: 'Muebles de la sala',
    content: {
      introduction: {
        title: 'Los muebles: La sala',
        goals: [
          'Выучить мебель для гостиной',
          'Научиться описывать интерьер',
          'Использовать предлоги места',
          'Говорить о покупке мебели',
        ],
        overview: 'Основная мебель гостиной для описания дома.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Muebles de sala',
        explanation: 'Мебель и предлоги места',
        examples: [
          { spanish: 'El sofá', russian: 'диван' },
          { spanish: 'La mesa', russian: 'стол' },
          { spanish: 'La silla', russian: 'стул' },
          { spanish: 'El sillón', russian: 'кресло' },
          { spanish: 'La estantería', russian: 'книжный шкаф/стеллаж' },
          { spanish: 'La lámpara', russian: 'лампа' },
          { spanish: 'El televisor', russian: 'телевизор' },
          { spanish: 'El sofá está junto a la ventana', russian: 'диван рядом с окном' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-77.mp3',
        transcript: 'En mi sala hay un sofá grande y cómodo. Frente al sofá está el televisor. Tengo dos sillones junto a la ventana. La mesa de centro está entre el sofá y la televisión. En la esquina hay una lámpara alta. La estantería está llena de libros.',
        questions: [
          {
            question: '¿Dónde está el televisor?',
            options: ['junto a la ventana', 'frente al sofá', 'en la esquina', 'en la estantería'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué hay en la esquina?',
            options: ['el sofá', 'el televisor', 'una lámpara', 'la estantería'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Necesito comprar un sofá nuevo',
          russian: 'Мне нужно купить новый диван',
          context: 'О покупках',
        },
        {
          spanish: 'El sillón es muy cómodo',
          russian: 'Кресло очень удобное',
          context: 'Описание',
        },
        {
          spanish: '¿Dónde pongo la lámpara?',
          russian: 'Куда поставить лампу?',
          context: 'Обустройство',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: false,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-77.mp3',
    readingText: 'Los MUEBLES de la sala son esenciales. El SOFÁ es para sentarse cómodamente. El SILLÓN es para una persona. La MESA (de centro, de café) está en el medio. Las SILLAS son para sentarse. La ESTANTERÍA guarda libros. La LÁMPARA da luz. El TELEVISOR es para entretenimiento. Preposiciones útiles: junto a (рядом с), frente a (напротив), entre (между), en la esquina (в углу).',
    duration: 28,
    order: 77,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-78',
    levelId: 'a1',
    title: 'Дом: Мебель спальни',
    description: 'Muebles del dormitorio',
    content: {
      introduction: {
        title: 'Los muebles: El dormitorio',
        goals: [
          'Выучить мебель спальни',
          'Научиться описывать спальню',
          'Говорить о сне и отдыхе',
          'Использовать глаголы dormir, descansar',
        ],
        overview: 'Мебель и предметы спальни для описания личного пространства.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Muebles de dormitorio',
        explanation: 'Мебель спальни и глаголы',
        examples: [
          { spanish: 'La cama', russian: 'кровать' },
          { spanish: 'El armario', russian: 'шкаф' },
          { spanish: 'La mesita de noche', russian: 'тумбочка' },
          { spanish: 'El espejo', russian: 'зеркало' },
          { spanish: 'La almohada', russian: 'подушка' },
          { spanish: 'Las sábanas', russian: 'простыни' },
          { spanish: 'Duermo ocho horas', russian: 'я сплю восемь часов' },
          { spanish: 'Descanso en mi cama', russian: 'я отдыхаю в своей кровати' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-78.mp3',
        transcript: 'Mi dormitorio es mi lugar favorito. Tengo una cama grande y cómoda con almohadas suaves. El armario está lleno de ropa. En la mesita de noche tengo una lámpara y un libro. Hay un espejo grande en la pared. Duermo bien aquí.',
        questions: [
          {
            question: '¿Cómo es la cama?',
            options: ['pequeña', 'grande y cómoda', 'dura', 'vieja'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué hay en la mesita de noche?',
            options: ['ropa', 'almohadas', 'una lámpara y un libro', 'un espejo'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Voy a dormir',
          russian: 'Я иду спать',
          context: 'Перед сном',
        },
        {
          spanish: 'Mi cama es muy cómoda',
          russian: 'Моя кровать очень удобная',
          context: 'Описание',
        },
        {
          spanish: 'Necesito cambiar las sábanas',
          russian: 'Мне нужно поменять простыни',
          context: 'Домашние дела',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-78.mp3',
    readingText: 'El DORMITORIO es donde duermes. La CAMA es lo más importante - puede ser individual (1 persona) o matrimonial (2 personas). El ARMARIO guarda la ropa. La MESITA DE NOCHE está junto a la cama. El ESPEJO sirve para mirarte. La ALMOHADA es para la cabeza. Las SÁBANAS cubren la cama. Verbos: DORMIR (спать), DESCANSAR (отдыхать), LEVANTARSE (вставать).',
    duration: 27,
    order: 78,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-79',
    levelId: 'a1',
    title: 'Дом: Кухня',
    description: 'Electrodomésticos y utensilios',
    content: {
      introduction: {
        title: 'La cocina',
        goals: [
          'Выучить бытовую технику',
          'Выучить кухонную утварь',
          'Научиться говорить о готовке',
          'Использовать в контексте кухни',
        ],
        overview: 'Предметы и техника на кухне для описания и использования.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: La cocina',
        explanation: 'Техника и утварь',
        examples: [
          { spanish: 'La nevera / El refrigerador', russian: 'холодильник' },
          { spanish: 'El horno', russian: 'духовка' },
          { spanish: 'La estufa / La cocina', russian: 'плита' },
          { spanish: 'El microondas', russian: 'микроволновка' },
          { spanish: 'El fregadero', russian: 'раковина' },
          { spanish: 'Los platos', russian: 'тарелки' },
          { spanish: 'Los vasos', russian: 'стаканы' },
          { spanish: 'Los cubiertos', russian: 'столовые приборы' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-79.mp3',
        transcript: 'Mi cocina tiene todos los electrodomésticos necesarios. La nevera guarda la comida fresca. Uso el horno para hornear. La estufa es para cocinar en ollas y sartenes. El microondas calienta rápido. Lavo los platos en el fregadero. Los vasos están en el armario.',
        questions: [
          {
            question: '¿Para qué usa el horno?',
            options: ['para lavar', 'para guardar comida', 'para hornear', 'para calentar rápido'],
            correctAnswer: 2,
          },
          {
            question: '¿Dónde lava los platos?',
            options: ['en la nevera', 'en el horno', 'en el microondas', 'en el fregadero'],
            correctAnswer: 3,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Pon la comida en la nevera',
          russian: 'Положи еду в холодильник',
          context: 'Инструкция',
        },
        {
          spanish: 'Calienta esto en el microondas',
          russian: 'Разогрей это в микроволновке',
          context: 'Просьба',
        },
        {
          spanish: 'Necesito lavar los platos',
          russian: 'Мне нужно помыть посуду',
          context: 'Домашние дела',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: false,
      },
    },
    audioUrl: '/audio/a1-79.mp3',
    readingText: 'La COCINA tiene muchos elementos. NEVERA/REFRIGERADOR (холодильник) mantiene fresco. HORNO (духовка) para hornear. ESTUFA/COCINA (плита) para cocinar. MICROONDAS (микроволновка) calienta rápido. FREGADERO (раковина) para lavar. PLATOS (тарелки), VASOS (стаканы), CUBIERTOS (столовые приборы: tenedor, cuchillo, cuchara). También: ollas, sartenes, tazas.',
    duration: 29,
    order: 79,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-80',
    levelId: 'a1',
    title: 'Дом: Ванная комната',
    description: 'El baño y artículos de higiene',
    content: {
      introduction: {
        title: 'El baño',
        goals: [
          'Выучить предметы ванной',
          'Выучить средства гигиены',
          'Научиться говорить о гигиене',
          'Использовать глаголы bañarse, ducharse',
        ],
        overview: 'Предметы ванной комнаты и средства гигиены.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: El baño',
        explanation: 'Предметы ванной и гигиены',
        examples: [
          { spanish: 'La ducha', russian: 'душ' },
          { spanish: 'La bañera', russian: 'ванна' },
          { spanish: 'El lavabo', russian: 'раковина (в ванной)' },
          { spanish: 'El inodoro', russian: 'унитаз' },
          { spanish: 'El champú', russian: 'шампунь' },
          { spanish: 'El jabón', russian: 'мыло' },
          { spanish: 'La toalla', russian: 'полотенце' },
          { spanish: 'Me ducho por la mañana', russian: 'я принимаю душ утром' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-80.mp3',
        transcript: 'Mi baño tiene ducha y bañera. Me ducho cada mañana con champú y jabón. El lavabo tiene un espejo grande. Las toallas están limpias. Guardo el champú en la ducha. El papel higiénico está junto al inodoro.',
        questions: [
          {
            question: '¿Cuándo se ducha?',
            options: ['por la noche', 'por la tarde', 'por la mañana', 'al mediodía'],
            correctAnswer: 2,
          },
          {
            question: '¿Qué hay en el lavabo?',
            options: ['toallas', 'champú', 'un espejo grande', 'jabón'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Voy a ducharme',
          russian: 'Я иду в душ',
          context: 'О намерении',
        },
        {
          spanish: 'Necesito champú nuevo',
          russian: 'Мне нужен новый шампунь',
          context: 'О покупках',
        },
        {
          spanish: 'Dame una toalla, por favor',
          russian: 'Дай мне полотенце, пожалуйста',
          context: 'Просьба',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-80.mp3',
    readingText: 'El BAÑO es para higiene personal. DUCHA (душ) para ducharse. BAÑERA (ванна) para bañarse. LAVABO (раковина) para lavarse las manos y cara. INODORO (унитаз). Artículos: CHAMPÚ (шампунь), JABÓN (мыло), TOALLA (полотенце), pasta de dientes (зубная паста), cepillo de dientes (зубная щетка). Verbos: DUCHARSE (принимать душ), BAÑARSE (принимать ванну), LAVARSE (мыться).',
    duration: 30,
    order: 80,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-81',
    levelId: 'a1',
    title: 'Типы жилья',
    description: 'Casa, apartamento, piso',
    content: {
      introduction: {
        title: 'Tipos de vivienda',
        goals: [
          'Выучить типы жилья',
          'Научиться описывать свое жилье',
          'Говорить об аренде и покупке',
          'Использовать глаголы vivir, alquilar',
        ],
        overview: 'Разные типы жилья и как о них говорить.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Tipos de vivienda',
        explanation: 'Типы домов и квартир',
        examples: [
          { spanish: 'La casa', russian: 'дом' },
          { spanish: 'El apartamento / El piso', russian: 'квартира' },
          { spanish: 'El estudio', russian: 'студия' },
          { spanish: 'El edificio', russian: 'здание' },
          { spanish: 'Vivo en un apartamento', russian: 'я живу в квартире' },
          { spanish: 'Alquilo un piso', russian: 'я арендую квартиру' },
          { spanish: 'Tengo casa propia', russian: 'у меня свой дом' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-81.mp3',
        transcript: 'Vivo en un apartamento en un edificio de cinco pisos. Alquilo un piso de dos dormitorios. Antes vivía en una casa con jardín. Mi hermano vive en un estudio pequeño. Algún día quiero comprar mi propia casa.',
        questions: [
          {
            question: '¿Dónde vive la persona ahora?',
            options: ['en una casa', 'en un apartamento', 'en un estudio', 'en un hotel'],
            correctAnswer: 1,
          },
          {
            question: '¿Dónde vive el hermano?',
            options: ['en una casa', 'en un apartamento grande', 'en un estudio', 'con los padres'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Busco apartamento para alquilar',
          russian: 'Ищу квартиру для аренды',
          context: 'Поиск жилья',
        },
        {
          spanish: 'Vivo en el tercer piso',
          russian: 'Я живу на третьем этаже',
          context: 'О местонахождении',
        },
        {
          spanish: 'Compré una casa el año pasado',
          russian: 'Я купил дом в прошлом году',
          context: 'О собственности',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: false,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-81.mp3',
    readingText: 'Hay diferentes tipos de vivienda. CASA (дом) - edificación independiente, puede tener jardín. APARTAMENTO o PISO (квартира) - vivienda en un edificio. ESTUDIO (студия) - apartamento pequeño de una habitación. EDIFICIO (здание) donde están los pisos. Puedes ALQUILAR (арендовать) o COMPRAR (купить). Vivir en casa vs vivir en apartamento - diferentes estilos de vida.',
    duration: 28,
    order: 81,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-82',
    levelId: 'a1',
    title: 'Домашние дела',
    description: 'Las tareas del hogar',
    content: {
      introduction: {
        title: 'Tareas domésticas',
        goals: [
          'Выучить названия домашних дел',
          'Научиться говорить об обязанностях',
          'Использовать глаголы limpiar, ordenar',
          'Распределять обязанности',
        ],
        overview: 'Домашние дела и как о них говорить.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Tareas del hogar',
        explanation: 'Глаголы домашних дел',
        examples: [
          { spanish: 'Limpiar la casa', russian: 'убирать дом' },
          { spanish: 'Ordenar la habitación', russian: 'убирать комнату' },
          { spanish: 'Lavar los platos', russian: 'мыть посуду' },
          { spanish: 'Hacer la cama', russian: 'заправлять кровать' },
          { spanish: 'Pasar la aspiradora', russian: 'пылесосить' },
          { spanish: 'Sacar la basura', russian: 'выносить мусор' },
          { spanish: 'Planchar la ropa', russian: 'гладить одежду' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-82.mp3',
        transcript: 'Los sábados limpio toda la casa. Primero ordeno mi habitación y hago la cama. Luego lavo los platos del desayuno. Paso la aspiradora en la sala. Mi hermano saca la basura. Mi madre plancha la ropa. Todos ayudamos en casa.',
        questions: [
          {
            question: '¿Cuándo limpia la casa?',
            options: ['los lunes', 'los viernes', 'los sábados', 'los domingos'],
            correctAnswer: 2,
          },
          {
            question: '¿Qué hace el hermano?',
            options: ['lava los platos', 'saca la basura', 'plancha', 'cocina'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Tengo que limpiar mi cuarto',
          russian: 'Мне нужно убрать свою комнату',
          context: 'Об обязанностях',
        },
        {
          spanish: '¿Quién lava los platos hoy?',
          russian: 'Кто сегодня моет посуду?',
          context: 'Распределение дел',
        },
        {
          spanish: 'Ayudo a mi madre con las tareas',
          russian: 'Я помогаю маме по дому',
          context: 'О помощи',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-82.mp3',
    readingText: 'Las tareas del hogar son necesarias. LIMPIAR (убирать) la casa. ORDENAR (приводить в порядок) las habitaciones. LAVAR LOS PLATOS (мыть посуду). HACER LA CAMA (заправлять кровать). PASAR LA ASPIRADORA (пылесосить). SACAR LA BASURA (выносить мусор). PLANCHAR (гладить). COCINAR (готовить). En muchas familias, todos comparten las tareas domésticas.',
    duration: 29,
    order: 82,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-83',
    levelId: 'a1',
    title: 'В магазине одежды',
    description: 'Comprando ropa - tallas y colores',
    content: {
      introduction: {
        title: 'De compras: La tienda de ropa',
        goals: [
          'Научиться спрашивать о размерах',
          'Выучить размеры одежды',
          'Практиковать примерку',
          'Использовать фразы в магазине',
        ],
        overview: 'Полезные фразы для покупки одежды.',
      },
      newWords: [],
      grammar: {
        title: 'Frases para comprar ropa',
        explanation: 'Размеры и примерка',
        examples: [
          { spanish: '¿Qué talla usas?', russian: 'какой у тебя размер?' },
          { spanish: 'Uso la talla M', russian: 'я ношу размер M' },
          { spanish: '¿Tienen esto en otra talla?', russian: 'у вас это есть в другом размере?' },
          { spanish: '¿Puedo probármelo?', russian: 'могу я это примерить?' },
          { spanish: 'Me queda bien / mal', russian: 'мне подходит / не подходит' },
          { spanish: 'Es muy grande / pequeño', russian: 'это слишком большое / маленькое' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-83.mp3',
        transcript: 'En la tienda de ropa: Buenas tardes, ¿puedo ayudarle? Sí, busco una camisa. ¿Qué talla usa? La talla M. ¿Tiene esta en azul? Sí, aquí está. ¿Puedo probármela? Claro, el probador está allí. Gracias. ¿Cómo le queda? Me queda perfecta. Me la llevo.',
        questions: [
          {
            question: '¿Qué talla usa la persona?',
            options: ['S', 'M', 'L', 'XL'],
            correctAnswer: 1,
          },
          {
            question: '¿De qué color quiere la camisa?',
            options: ['blanca', 'azul', 'roja', 'negra'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Esto está en rebaja?',
          russian: 'Это со скидкой?',
          context: 'О ценах',
        },
        {
          spanish: 'Me gusta pero es muy caro',
          russian: 'Мне нравится, но это очень дорого',
          context: 'Обсуждение цены',
        },
        {
          spanish: '¿Aceptan tarjeta?',
          russian: 'Вы принимаете карту?',
          context: 'При оплате',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: false,
      },
    },
    audioUrl: '/audio/a1-83.mp3',
    readingText: 'Cuando compras ropa, preguntas importantes: ¿Qué TALLA usa? Tallas: XS, S, M, L, XL. ¿Tienen esto en otra talla/color? ¿Puedo PROBÁRMELO? (примерить). El PROBADOR es donde te pruebas la ropa. Si te QUEDA BIEN (подходит), lo compras. Si te QUEDA MAL o es muy grande/pequeño, pides otra talla. También: ¿Cuánto cuesta? ¿Está en rebaja?',
    duration: 31,
    order: 83,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-84',
    levelId: 'a1',
    title: 'Описание дома мечты',
    description: 'Mi casa ideal',
    content: {
      introduction: {
        title: 'La casa de mis sueños',
        goals: [
          'Практиковать описание идеального дома',
          'Использовать условное наклонение',
          'Выражать желания (Me gustaría...)',
          'Объединить всю лексику жилья',
        ],
        overview: 'Практикуем описание дома мечты, используя всю изученную лексику.',
      },
      newWords: [],
      grammar: {
        title: 'Describiendo la casa ideal',
        explanation: 'Использование Me gustaría, Quisiera, Tendría',
        examples: [
          { spanish: 'Me gustaría tener una casa grande', russian: 'мне бы хотелось иметь большой дом' },
          { spanish: 'Quisiera un jardín amplio', russian: 'я бы хотел просторный сад' },
          { spanish: 'Tendría cuatro dormitorios', russian: 'в нем было бы четыре спальни' },
          { spanish: 'Mi casa ideal estaría en la playa', russian: 'мой идеальный дом был бы на пляже' },
          { spanish: 'Sueño con una cocina moderna', russian: 'я мечтаю о современной кухне' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-84.mp3',
        transcript: 'Mi casa ideal sería grande y luminosa. Tendría cuatro dormitorios y tres baños. Me gustaría tener una cocina moderna con todos los electrodomésticos nuevos. Quisiera una sala espaciosa con grandes ventanas. Lo más importante: tendría un jardín grande con árboles y flores. Estaría en un lugar tranquilo, cerca de la naturaleza.',
        questions: [
          {
            question: '¿Cuántos dormitorios tendría?',
            options: ['dos', 'tres', 'cuatro', 'cinco'],
            correctAnswer: 2,
          },
          {
            question: '¿Dónde estaría la casa?',
            options: ['en la ciudad', 'en la playa', 'en un lugar tranquilo', 'en la montaña'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Mi casa perfecta tendría piscina',
          russian: 'В моем идеальном доме был бы бассейн',
          context: 'О мечтах',
        },
        {
          spanish: 'Algún día compraré mi casa soñada',
          russian: 'Когда-нибудь я куплю дом своей мечты',
          context: 'О планах на будущее',
        },
        {
          spanish: '¿Cómo sería tu casa ideal?',
          russian: 'Каким был бы твой идеальный дом?',
          context: 'Вопрос о мечтах',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-84.mp3',
    readingText: 'Describir la casa ideal es un buen ejercicio. Usa: ME GUSTARÍA (мне бы хотелось), QUISIERA (я бы хотел), TENDRÍA (было бы), ESTARÍA (находился бы). Describe: número de habitaciones, tipo de cocina, baños, jardín o no, ubicación (en la ciudad, en el campo, en la playa). Puedes soñar con: piscina, biblioteca, gimnasio en casa. ¡La imaginación no tiene límites!',
    duration: 32,
    order: 84,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-85',
    levelId: 'a1',
    title: 'Итоговая практика: Дом и одежда',
    description: 'Repaso completo',
    content: {
      introduction: {
        title: 'Repaso: Cuerpo, ropa y casa',
        goals: [
          'Повторить всю лексику раздела',
          'Практиковать в комплексных диалогах',
          'Объединить все темы',
          'Подготовиться к использованию в жизни',
        ],
        overview: 'Финальная практика всех тем: тело, одежда, дом.',
      },
      newWords: [],
      grammar: {
        title: 'Repaso general',
        explanation: 'Все изученные темы вместе',
        examples: [
          { spanish: 'Vivo en una casa con tres habitaciones', russian: 'я живу в доме с тремя комнатами' },
          { spanish: 'Hoy llevo una camisa azul', russian: 'сегодня я ношу синюю рубашку' },
          { spanish: 'Me duele la cabeza', russian: 'у меня болит голова' },
          { spanish: 'Necesito limpiar mi dormitorio', russian: 'мне нужно убрать свою спальню' },
          { spanish: 'Voy a comprar zapatos nuevos', russian: 'я собираюсь купить новые туфли' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-85.mp3',
        transcript: 'Hoy es sábado. Me levanto a las 9, me ducho y me pongo ropa cómoda: unos vaqueros y una camiseta. Después del desayuno, limpio la casa. Ordeno mi dormitorio, hago la cama, paso la aspiradora en la sala. A las 12 salgo de compras. Necesito una chaqueta nueva para el invierno. En la tienda encuentro una perfecta, talla M, color negro. Me la pruebo y me queda bien. La compro y vuelvo a casa feliz.',
        questions: [
          {
            question: '¿Qué ropa se pone por la mañana?',
            options: ['camisa formal', 'vaqueros y camiseta', 'vestido', 'traje'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué compra en la tienda?',
            options: ['zapatos', 'pantalones', 'una chaqueta', 'una camiseta'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Después de limpiar, descansaré',
          russian: 'После уборки я отдохну',
          context: 'Планирование дня',
        },
        {
          spanish: 'En mi armario hay mucha ropa',
          russian: 'В моем шкафу много одежды',
          context: 'Описание',
        },
        {
          spanish: 'Mi casa está siempre limpia',
          russian: 'Мой дом всегда чистый',
          context: 'Характеристика',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-85.mp3',
    readingText: 'Ahora puedes hablar sobre tu cuerpo, tu ropa y tu casa en español. Puedes describir tu apariencia física, decir qué ropa llevas, describir las habitaciones de tu casa, los muebles que tienes, las tareas que haces. Puedes ir de compras y comunicarte en tiendas. Puedes expresar dolor o malestar. Toda esta vocabulario es esencial para la vida diaria. ¡Practica todos los días!',
    duration: 33,
    order: 85,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
