import { Lesson } from '@/types'

// A1 Lessons: Food and Drinks (Lessons 61-70)
export const a1LessonsFoodDrinks: Lesson[] = [
  // ==================== ЕДА И НАПИТКИ (10 УРОКОВ) ====================
  {
    id: 'a1-61',
    levelId: 'a1',
    title: 'Еда: Фрукты',
    description: 'Учим названия популярных фруктов',
    content: {
      introduction: {
        title: 'Las frutas',
        goals: [
          'Выучить названия 15 популярных фруктов',
          'Научиться говорить о предпочтениях во фруктах',
          'Использовать в контексте покупок',
          'Практиковать вопросы в магазине',
        ],
        overview: 'Фрукты - важная часть испанской кухни. Учим их названия и как о них говорить.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Frutas',
        explanation: 'Названия фруктов и фразы для покупок',
        examples: [
          { spanish: 'La manzana', russian: 'яблоко' },
          { spanish: 'La naranja', russian: 'апельсин' },
          { spanish: 'El plátano', russian: 'банан' },
          { spanish: 'La pera', russian: 'груша' },
          { spanish: 'Las fresas', russian: 'клубника' },
          { spanish: 'Las uvas', russian: 'виноград' },
          { spanish: 'El limón', russian: 'лимон' },
          { spanish: 'La sandía', russian: 'арбуз' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-61.mp3',
        transcript: 'En el mercado hay muchas frutas. Me gustan las manzanas rojas. Mi hermano prefiere los plátanos. Las naranjas son buenas para el zumo. Las fresas están deliciosas. ¿Qué frutas te gustan?',
        questions: [
          {
            question: '¿Qué frutas le gustan al que habla?',
            options: ['los plátanos', 'las manzanas rojas', 'las naranjas', 'las fresas'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué prefiere el hermano?',
            options: ['las manzanas', 'los plátanos', 'las naranjas', 'las uvas'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Quiero un kilo de manzanas',
          russian: 'Я хочу килограмм яблок',
          context: 'В магазине',
        },
        {
          spanish: 'Las frutas son saludables',
          russian: 'Фрукты полезны',
          context: 'О здоровье',
        },
        {
          spanish: '¿Cuál es tu fruta favorita?',
          russian: 'Какой твой любимый фрукт?',
          context: 'Вопрос о предпочтениях',
        },
      ],
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-61.mp3',
    readingText: 'Las frutas son importantes en la dieta mediterránea. En España se come mucha fruta. Las MANZANAS y NARANJAS son muy populares. El PLÁTANO de Canarias es famoso. Las FRESAS de Huelva son deliciosas. En verano comemos SANDÍA y MELÓN. En otoño, UVAS. Las frutas tienen vitaminas y son muy saludables.',
    duration: 28,
    order: 61,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-62',
    levelId: 'a1',
    title: 'Еда: Овощи',
    description: 'Названия овощей и зелени',
    content: {
      introduction: {
        title: 'Las verduras y hortalizas',
        goals: [
          'Выучить названия овощей',
          'Различать verduras y hortalizas',
          'Научиться говорить о салатах',
          'Использовать в контексте готовки',
        ],
        overview: 'Овощи - основа здорового питания. Учим их названия на испанском.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Verduras',
        explanation: 'Овощи и как их использовать в речи',
        examples: [
          { spanish: 'El tomate', russian: 'помидор' },
          { spanish: 'La lechuga', russian: 'салат (латук)' },
          { spanish: 'La zanahoria', russian: 'морковь' },
          { spanish: 'El pepino', russian: 'огурец' },
          { spanish: 'La cebolla', russian: 'лук' },
          { spanish: 'El pimiento', russian: 'перец' },
          { spanish: 'Las patatas', russian: 'картофель' },
          { spanish: 'El ajo', russian: 'чеснок' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-62.mp3',
        transcript: 'Para hacer una ensalada necesito lechuga, tomates y pepinos. También añado cebolla y zanahoria. Las patatas son muy versátiles. El ajo y la cebolla son la base de muchos platos españoles.',
        questions: [
          {
            question: '¿Qué verduras necesita para la ensalada?',
            options: ['solo lechuga', 'lechuga, tomates y pepinos', 'solo tomates', 'patatas'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué son la base de muchos platos españoles?',
            options: ['las patatas', 'los tomates', 'el ajo y la cebolla', 'los pepinos'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Necesito comprar verduras frescas',
          russian: 'Мне нужно купить свежие овощи',
          context: 'Планирование покупок',
        },
        {
          spanish: 'Una ensalada de tomate con cebolla',
          russian: 'Салат из помидоров с луком',
          context: 'Заказ в ресторане',
        },
        {
          spanish: 'Como verduras todos los días',
          russian: 'Я ем овощи каждый день',
          context: 'О привычках питания',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: false,
      },
    },
    audioUrl: '/audio/a1-62.mp3',
    readingText: 'Las verduras son esenciales en la cocina española. El TOMATE es el rey - se usa en gazpacho, ensaladas, salsas. Las PATATAS son muy populares: patatas fritas, tortilla de patatas. La CEBOLLA y el AJO son la base del sofrito. Los PIMIENTOS se usan mucho, especialmente los pimientos rojos. Una ensalada típica lleva LECHUGA, TOMATE, CEBOLLA y PEPINO.',
    duration: 27,
    order: 62,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-63',
    levelId: 'a1',
    title: 'Еда: Мясо и рыба',
    description: 'Виды мяса и морепродуктов',
    content: {
      introduction: {
        title: 'Carne y pescado',
        goals: [
          'Выучить названия видов мяса',
          'Выучить названия рыбы и морепродуктов',
          'Научиться заказывать в ресторане',
          'Говорить о способах приготовления',
        ],
        overview: 'Мясо и рыба - важные источники белка. Учим как о них говорить.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Carne y Pescado',
        explanation: 'Мясо, рыба и способы приготовления',
        examples: [
          { spanish: 'El pollo', russian: 'курица' },
          { spanish: 'La carne de res', russian: 'говядина' },
          { spanish: 'El cerdo', russian: 'свинина' },
          { spanish: 'El cordero', russian: 'баранина' },
          { spanish: 'El pescado', russian: 'рыба' },
          { spanish: 'El salmón', russian: 'лосось' },
          { spanish: 'Los camarones', russian: 'креветки' },
          { spanish: 'A la plancha / Frito / Al horno', russian: 'на гриле / жареное / в духовке' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-63.mp3',
        transcript: 'En el restaurante hay muchas opciones. Puedes pedir pollo a la plancha o pescado al horno. La carne de res está muy buena aquí. También tienen mariscos frescos: camarones, mejillones. Yo prefiero el salmón.',
        questions: [
          {
            question: '¿Cómo se puede pedir el pollo?',
            options: ['solo frito', 'a la plancha', 'solo al horno', 'solo crudo'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué prefiere la persona?',
            options: ['el pollo', 'la carne de res', 'el salmón', 'los camarones'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Quiero un filete de ternera',
          russian: 'Я хочу стейк из телятины',
          context: 'Заказ в ресторане',
        },
        {
          spanish: 'El pescado está fresco hoy',
          russian: 'Рыба сегодня свежая',
          context: 'В ресторане/магазине',
        },
        {
          spanish: 'Soy vegetariano, no como carne',
          russian: 'Я вегетарианец, не ем мясо',
          context: 'Диетические предпочтения',
        },
      ],
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-63.mp3',
    readingText: 'España es famosa por sus productos del mar y carne de calidad. El JAMÓN ibérico es un producto premium. El POLLO y el CERDO son carnes comunes. En la costa se come mucho PESCADO y MARISCOS. El SALMÓN, el ATÚN, los CAMARONES son populares. Formas de cocinar: A LA PLANCHA (гриль), FRITO (жареное), AL HORNO (запеченное), COCIDO (вареное).',
    duration: 29,
    order: 63,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-64',
    levelId: 'a1',
    title: 'Напитки: Горячие и холодные',
    description: 'Все виды напитков',
    content: {
      introduction: {
        title: 'Las bebidas',
        goals: [
          'Выучить названия напитков',
          'Различать bebidas calientes y frías',
          'Научиться заказывать напитки',
          'Использовать в кафе и ресторане',
        ],
        overview: 'Напитки - неотъемлемая часть культуры питания. Учим как их заказывать.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Bebidas',
        explanation: 'Горячие и холодные напитки',
        examples: [
          { spanish: 'El café', russian: 'кофе' },
          { spanish: 'El té', russian: 'чай' },
          { spanish: 'El agua', russian: 'вода' },
          { spanish: 'El zumo / El jugo', russian: 'сок' },
          { spanish: 'La leche', russian: 'молоко' },
          { spanish: 'El vino', russian: 'вино' },
          { spanish: 'La cerveza', russian: 'пиво' },
          { spanish: 'El refresco', russian: 'прохладительный напиток' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-64.mp3',
        transcript: 'En el bar pido un café con leche. Mi amigo prefiere té. Para beber con la comida, queremos agua mineral. También tienen zumo de naranja natural. Por la noche tomamos una cerveza o una copa de vino.',
        questions: [
          {
            question: '¿Qué pide la persona en el bar?',
            options: ['té', 'café con leche', 'agua', 'zumo'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué beben con la comida?',
            options: ['café', 'té', 'agua mineral', 'vino'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Un café solo, por favor',
          russian: 'Черный кофе, пожалуйста',
          context: 'Заказ в кафе',
        },
        {
          spanish: '¿Quieres algo de beber?',
          russian: 'Хочешь что-нибудь выпить?',
          context: 'Предложение',
        },
        {
          spanish: 'Bebo mucha agua todos los días',
          russian: 'Я пью много воды каждый день',
          context: 'О привычках',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-64.mp3',
    readingText: 'Las bebidas son muy variadas. El CAFÉ es muy popular en España - café solo, café con leche, cortado. El TÉ se bebe menos que el café. El AGUA es esencial - agua con gas o sin gas. Los ZUMOS naturales son comunes en el desayuno. El VINO es parte de la cultura: vino tinto, blanco, rosado. La CERVEZA se bebe mucho, especialmente en verano.',
    duration: 28,
    order: 64,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-65',
    levelId: 'a1',
    title: 'Еда: Хлеб и выпечка',
    description: 'Pan, pasteles y postres',
    content: {
      introduction: {
        title: 'Pan y dulces',
        goals: [
          'Выучить названия хлеба и выпечки',
          'Научиться заказывать в пекарне',
          'Говорить о десертах',
          'Использовать в контексте завтрака',
        ],
        overview: 'Хлеб и выпечка - важная часть испанского питания, особенно на завтрак.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Pan y Dulces',
        explanation: 'Хлеб, выпечка и десерты',
        examples: [
          { spanish: 'El pan', russian: 'хлеб' },
          { spanish: 'La baguette / La barra', russian: 'багет' },
          { spanish: 'El croissant', russian: 'круассан' },
          { spanish: 'Las galletas', russian: 'печенье' },
          { spanish: 'El pastel / La tarta', russian: 'торт/пирог' },
          { spanish: 'Los churros', russian: 'чуррос' },
          { spanish: 'El flan', russian: 'флан (десерт)' },
          { spanish: 'El helado', russian: 'мороженое' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-65.mp3',
        transcript: 'En la panadería compro pan fresco cada día. Para el desayuno me gustan los croissants. Los churros con chocolate son deliciosos. De postre prefiero el flan o el helado. Las galletas son buenas para la merienda.',
        questions: [
          {
            question: '¿Qué compra cada día?',
            options: ['croissants', 'pan fresco', 'churros', 'galletas'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué le gusta para el desayuno?',
            options: ['el pan', 'los croissants', 'las galletas', 'los churros'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Una barra de pan, por favor',
          russian: 'Багет, пожалуйста',
          context: 'В пекарне',
        },
        {
          spanish: 'Los churros con chocolate están riquísimos',
          russian: 'Чуррос с шоколадом очень вкусные',
          context: 'Комплимент еде',
        },
        {
          spanish: '¿Qué postre recomiendas?',
          russian: 'Какой десерт рекомендуешь?',
          context: 'В ресторане',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: false,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-65.mp3',
    readingText: 'El PAN es fundamental en España. Se come en todas las comidas. El pan fresco se compra diariamente en la panadería. Los CHURROS con chocolate son un desayuno típico español. Los CROISSANTS son populares para el desayuno. Los PASTELES y TARTAS se comen en ocasiones especiales. El FLAN es un postre tradicional. El HELADO se come mucho en verano.',
    duration: 27,
    order: 65,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-66',
    levelId: 'a1',
    title: 'Приемы пищи: Завтрак, обед, ужин',
    description: 'Desayuno, comida, cena',
    content: {
      introduction: {
        title: 'Las comidas del día',
        goals: [
          'Выучить названия приемов пищи',
          'Понять испанское расписание еды',
          'Научиться говорить о своих привычках питания',
          'Использовать глаголы desayunar, comer, cenar',
        ],
        overview: 'В Испании особое расписание приемов пищи. Учим как об этом говорить.',
      },
      newWords: [],
      grammar: {
        title: 'Las comidas + verbos',
        explanation: 'Desayuno/Desayunar, Comida/Comer, Cena/Cenar',
        examples: [
          { spanish: 'El desayuno (desayunar)', russian: 'завтрак (завтракать)' },
          { spanish: 'La comida (comer)', russian: 'обед (обедать)' },
          { spanish: 'La cena (cenar)', russian: 'ужин (ужинать)' },
          { spanish: 'La merienda', russian: 'полдник' },
          { spanish: 'Desayuno a las 8', russian: 'я завтракаю в 8' },
          { spanish: 'Como a las 2', russian: 'я обедаю в 2' },
          { spanish: 'Ceno a las 9', russian: 'я ужинаю в 9' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-66.mp3',
        transcript: 'Mi rutina de comidas: Desayuno a las 8 de la mañana - café con tostadas. Como a las 2 de la tarde - es la comida principal. A las 5 tomo la merienda - galletas o fruta. Ceno a las 9 de la noche - algo ligero. ¿Y tú, a qué hora comes?',
        questions: [
          {
            question: '¿A qué hora desayuna?',
            options: ['a las 7', 'a las 8', 'a las 9', 'a las 10'],
            correctAnswer: 1,
          },
          {
            question: '¿Cuál es la comida principal?',
            options: ['el desayuno', 'la comida (almuerzo)', 'la merienda', 'la cena'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Qué desayunas normalmente?',
          russian: 'Что ты обычно ешь на завтрак?',
          context: 'Вопрос о привычках',
        },
        {
          spanish: 'La comida es a las 2',
          russian: 'Обед в 2 часа',
          context: 'О расписании',
        },
        {
          spanish: '¿Cenamos juntos esta noche?',
          russian: 'Поужинаем вместе сегодня вечером?',
          context: 'Приглашение',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-66.mp3',
    readingText: 'En España, las comidas tienen horarios diferentes. El DESAYUNO (7-9 AM) es ligero: café con tostadas o croissant. La COMIDA o ALMUERZO (2-3 PM) es la comida principal del día. La MERIENDA (5-6 PM) es un snack pequeño. La CENA (9-10 PM) es más tarde que en otros países. Verbos: DESAYUNAR, COMER, MERENDAR, CENAR.',
    duration: 30,
    order: 66,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-67',
    levelId: 'a1',
    title: 'В ресторане: Заказ еды',
    description: 'Как заказать еду и напитки',
    content: {
      introduction: {
        title: 'En el restaurante',
        goals: [
          'Научиться заказывать еду',
          'Выучить фразы для ресторана',
          'Понять меню на испанском',
          'Практиковать вежливые просьбы',
        ],
        overview: 'Важные фразы для посещения ресторана в испаноязычных странах.',
      },
      newWords: [],
      grammar: {
        title: 'Frases para el restaurante',
        explanation: 'Стандартные фразы для заказа и общения с официантом',
        examples: [
          { spanish: 'La carta / El menú', russian: 'меню' },
          { spanish: 'Quisiera...', russian: 'я бы хотел...' },
          { spanish: 'Para mí...', russian: 'для меня...' },
          { spanish: 'La cuenta, por favor', russian: 'счет, пожалуйста' },
          { spanish: '¿Qué recomienda?', russian: 'что рекомендуете?' },
          { spanish: 'De primero / De segundo / De postre', russian: 'первое / второе / десерт' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-67.mp3',
        transcript: 'Buenas tardes. ¿Tiene una mesa para dos? Sí, por aquí. La carta, por favor. De primero, una ensalada. De segundo, quisiera el pescado a la plancha. Para beber, agua mineral. ¿Y de postre? Un flan, por favor. La cuenta, por favor.',
        questions: [
          {
            question: '¿Para cuántas personas es la mesa?',
            options: ['una', 'dos', 'tres', 'cuatro'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué pide de segundo?',
            options: ['ensalada', 'carne', 'pescado a la plancha', 'pollo'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Quisiera reservar una mesa',
          russian: 'Я бы хотел забронировать столик',
          context: 'Бронирование',
        },
        {
          spanish: 'El plato del día, por favor',
          russian: 'Блюдо дня, пожалуйста',
          context: 'Заказ',
        },
        {
          spanish: '¿Está incluido el servicio?',
          russian: 'Обслуживание включено?',
          context: 'При оплате',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-67.mp3',
    readingText: 'Para comer en un restaurante en España, estas frases son esenciales. Pedir la mesa: "Una mesa para X personas". Pedir la CARTA (меню). Ordenar: "Quisiera..." o "Para mí...". Estructura del menú: PRIMERO (первое), SEGUNDO (второе), POSTRE (десерт). Al final: "La cuenta, por favor". Es común dejar propina (5-10%).',
    duration: 31,
    order: 67,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-68',
    levelId: 'a1',
    title: 'Вкусы: Описываем еду',
    description: 'Прилагательные для описания вкуса',
    content: {
      introduction: {
        title: 'Los sabores',
        goals: [
          'Выучить прилагательные вкуса',
          'Научиться описывать еду',
          'Использовать глагол ESTAR для вкуса',
          'Выражать мнение о еде',
        ],
        overview: 'Учимся описывать, какая еда на вкус, используя правильные прилагательные.',
      },
      newWords: [],
      grammar: {
        title: 'Adjetivos de sabor',
        explanation: 'Está + прилагательное для описания вкуса',
        examples: [
          { spanish: 'Está rico / delicioso', russian: 'вкусно / очень вкусно' },
          { spanish: 'Está bueno', russian: 'хорошо / вкусно' },
          { spanish: 'Está dulce', russian: 'сладко' },
          { spanish: 'Está salado', russian: 'соленое' },
          { spanish: 'Está picante', russian: 'острое' },
          { spanish: 'Está amargo', russian: 'горькое' },
          { spanish: 'Está ácido', russian: 'кислое' },
          { spanish: 'Está malo', russian: 'невкусно / плохое' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-68.mp3',
        transcript: 'Esta paella está deliciosa. La sopa está un poco salada. El postre está muy dulce. El café está amargo, necesita azúcar. La salsa picante está muy picante. ¿Cómo está tu plato? Está rico, gracias.',
        questions: [
          {
            question: '¿Cómo está la paella?',
            options: ['salada', 'deliciosa', 'picante', 'amarga'],
            correctAnswer: 1,
          },
          {
            question: '¿Cómo está el café?',
            options: ['dulce', 'salado', 'amargo', 'ácido'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: '¡Qué rico está!',
          russian: 'Как вкусно!',
          context: 'Комплимент еде',
        },
        {
          spanish: 'Está demasiado picante para mí',
          russian: 'Для меня это слишком острое',
          context: 'Выражение дискомфорта',
        },
        {
          spanish: 'La comida está exquisita',
          russian: 'Еда изысканная',
          context: 'Высокая похвала',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: false,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-68.mp3',
    readingText: 'Para describir comida usamos el verbo ESTAR. RICO/DELICIOSO = вкусный. BUENO = хороший. DULCE = сладкий (azúcar). SALADO = соленый (sal). PICANTE = острый (chile, pimienta). AMARGO = горький (café sin azúcar). ÁCIDO = кислый (limón). Si no te gusta: "No me gusta" o "Está malo". Expresión común: "¡Qué rico!" (как вкусно!).',
    duration: 29,
    order: 68,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-69',
    levelId: 'a1',
    title: 'Глаголы готовки',
    description: 'Cocinar, preparar, hacer',
    content: {
      introduction: {
        title: 'Verbos de cocina',
        goals: [
          'Выучить глаголы, связанные с готовкой',
          'Научиться говорить о процессе приготовления',
          'Использовать в контексте рецептов',
          'Практиковать инструкции',
        ],
        overview: 'Основные глаголы для описания процесса приготовления пищи.',
      },
      newWords: [],
      grammar: {
        title: 'Verbos de cocina',
        explanation: 'Глаголы приготовления еды',
        examples: [
          { spanish: 'Cocinar', russian: 'готовить' },
          { spanish: 'Preparar', russian: 'готовить/подготавливать' },
          { spanish: 'Hacer', russian: 'делать/готовить' },
          { spanish: 'Freír', russian: 'жарить' },
          { spanish: 'Hervir', russian: 'кипятить/варить' },
          { spanish: 'Hornear', russian: 'запекать' },
          { spanish: 'Cortar', russian: 'резать' },
          { spanish: 'Mezclar', russian: 'смешивать' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-69.mp3',
        transcript: 'Me gusta cocinar. Para preparar una tortilla, necesito cortar las patatas, freírlas en aceite, mezclar con huevos y cocinar todo junto. Para hacer pasta, hay que hervir agua primero. Mi madre cocina muy bien. Ella prepara platos deliciosos.',
        questions: [
          {
            question: '¿Qué necesita hacer con las patatas?',
            options: ['hervirlas', 'cortarlas', 'hornearlas', 'mezclarlas'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué hace bien la madre?',
            options: ['cortar', 'freír', 'cocinar', 'hervir'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Voy a cocinar una paella',
          russian: 'Я собираюсь приготовить паэлью',
          context: 'О планах',
        },
        {
          spanish: '¿Sabes cocinar?',
          russian: 'Ты умеешь готовить?',
          context: 'Вопрос о навыках',
        },
        {
          spanish: 'Primero, corta las verduras',
          russian: 'Сначала порежь овощи',
          context: 'Инструкция',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-69.mp3',
    readingText: 'Los verbos de cocina son útiles. COCINAR y PREPARAR son sinónimos generales. HACER se usa con platos específicos: hacer una paella, hacer una tortilla. FREÍR = жарить en aceite. HERVIR = варить en agua. HORNEAR = готовить en el horno. CORTAR = резать con cuchillo. MEZCLAR = смешивать ingredientes. Para dar instrucciones: "Primero corta, luego mezcla, después cocina".',
    duration: 28,
    order: 69,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-70',
    levelId: 'a1',
    title: 'Диеты и предпочтения',
    description: 'Vegetariano, vegano, alérgico',
    content: {
      introduction: {
        title: 'Preferencias alimentarias',
        goals: [
          'Выучить слова о диетах',
          'Научиться говорить об аллергиях',
          'Объяснять свои предпочтения',
          'Использовать в ресторанах',
        ],
        overview: 'Важно уметь объяснить свои диетические ограничения и предпочтения.',
      },
      newWords: [],
      grammar: {
        title: 'Dietas y restricciones',
        explanation: 'Как говорить о диетических предпочтениях',
        examples: [
          { spanish: 'Soy vegetariano/a', russian: 'я вегетарианец/вегетарианка' },
          { spanish: 'Soy vegano/a', russian: 'я веган' },
          { spanish: 'Soy alérgico/a a...', russian: 'у меня аллергия на...' },
          { spanish: 'No como carne', russian: 'я не ем мясо' },
          { spanish: 'No puedo comer...', russian: 'я не могу есть...' },
          { spanish: 'Sin gluten / Sin lactosa', russian: 'без глютена / без лактозы' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-70.mp3',
        transcript: 'Soy vegetariana, así que no como carne ni pescado. Mi hermano es vegano - no come nada de origen animal. Mi amiga es alérgica a los frutos secos. En el restaurante pregunto: "¿Tienen opciones vegetarianas?" Es importante informar al camarero sobre alergias.',
        questions: [
          {
            question: '¿Qué tipo de dieta sigue la persona?',
            options: ['vegana', 'vegetariana', 'sin gluten', 'normal'],
            correctAnswer: 1,
          },
          {
            question: '¿A qué es alérgica la amiga?',
            options: ['a la lactosa', 'al gluten', 'a los frutos secos', 'al pescado'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Tiene opciones sin gluten?',
          russian: 'У вас есть варианты без глютена?',
          context: 'В ресторане',
        },
        {
          spanish: 'Soy alérgico al marisco',
          russian: 'У меня аллергия на морепродукты',
          context: 'Важная информация',
        },
        {
          spanish: 'Prefiero comida saludable',
          russian: 'Я предпочитаю здоровую еду',
          context: 'О предпочтениях',
        },
      ],
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-70.mp3',
    readingText: 'Es importante poder expresar tus restricciones alimentarias. VEGETARIANO = no come carne ni pescado, pero puede comer huevos y lácteos. VEGANO = no come nada de origen animal. Si eres ALÉRGICO, debes informarlo: "Soy alérgico a los frutos secos / al gluten / a la lactosa". En restaurantes: "¿Tienen opciones vegetarianas/veganas/sin gluten?" Es cada vez más común encontrar estas opciones.',
    duration: 30,
    order: 70,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
