import { Lesson } from '@/types'

// A1 Lessons: City, Transport, Daily Routine (Lessons 86-100)
export const a1LessonsCityTransportDaily: Lesson[] = [
  // ==================== ГОРОД, ТРАНСПОРТ, ПОВСЕДНЕВНАЯ ЖИЗНЬ (15 УРОКОВ) ====================
  {
    id: 'a1-86',
    levelId: 'a1',
    title: 'В городе: Места',
    description: 'Lugares en la ciudad',
    content: {
      introduction: {
        title: 'Lugares de la ciudad',
        goals: [
          'Выучить основные места в городе',
          'Научиться спрашивать дорогу',
          'Использовать глагол ESTAR для местоположения',
          'Практиковать предлоги места',
        ],
        overview: 'Основные места в городе для ориентации и общения.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Lugares',
        explanation: 'Места в городе и как их найти',
        examples: [
          { spanish: 'La plaza', russian: 'площадь' },
          { spanish: 'La calle', russian: 'улица' },
          { spanish: 'El parque', russian: 'парк' },
          { spanish: 'El supermercado', russian: 'супермаркет' },
          { spanish: 'El banco', russian: 'банк' },
          { spanish: 'La farmacia', russian: 'аптека' },
          { spanish: 'El hospital', russian: 'больница' },
          { spanish: '¿Dónde está el banco?', russian: 'где находится банк?' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-86.mp3',
        transcript: 'Mi ciudad tiene todo lo necesario. En el centro hay una plaza grande. Cerca está el supermercado donde compro comida. El banco está en la calle principal. La farmacia está al lado del hospital. El parque es perfecto para pasear.',
        questions: [
          {
            question: '¿Qué hay en el centro?',
            options: ['un supermercado', 'una plaza grande', 'un banco', 'un hospital'],
            correctAnswer: 1,
          },
          {
            question: '¿Dónde está la farmacia?',
            options: ['en la plaza', 'al lado del hospital', 'en el parque', 'lejos del centro'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Dónde está la estación de tren?',
          russian: 'Где находится железнодорожная станция?',
          context: 'Спрашивая дорогу',
        },
        {
          spanish: 'El supermercado está cerca',
          russian: 'Супермаркет рядом',
          context: 'Указание направления',
        },
        {
          spanish: 'Voy al parque a caminar',
          russian: 'Я иду в парк погулять',
          context: 'О планах',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-86.mp3',
    readingText: 'Lugares importantes en la ciudad: PLAZA (площадь) - centro de reunión. CALLE (улица) donde caminas. PARQUE (парк) para naturaleza. SUPERMERCADO (супермаркет) para compras. BANCO (банк) para dinero. FARMACIA (аптека) para medicinas. HOSPITAL (больница) para salud. Para preguntar: ¿Dónde está...? Está cerca/lejos, a la derecha/izquierda, todo recto.',
    duration: 28,
    order: 86,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-87',
    levelId: 'a1',
    title: 'Спрашиваем дорогу',
    description: 'Pedir y dar direcciones',
    content: {
      introduction: {
        title: 'Cómo pedir direcciones',
        goals: [
          'Научиться спрашивать дорогу',
          'Понимать указания направлений',
          'Выучить полезные фразы',
          'Использовать императив для указаний',
        ],
        overview: 'Важные фразы для ориентации в городе.',
      },
      newWords: [],
      grammar: {
        title: 'Frases para direcciones',
        explanation: 'Как спросить и понять направления',
        examples: [
          { spanish: '¿Cómo llego a...?', russian: 'как добраться до...?' },
          { spanish: 'Sigue todo recto', russian: 'иди прямо' },
          { spanish: 'Gira a la derecha', russian: 'поверни направо' },
          { spanish: 'Gira a la izquierda', russian: 'поверни налево' },
          { spanish: 'Está al final de la calle', russian: 'это в конце улицы' },
          { spanish: 'Cruza la calle', russian: 'перейди улицу' },
          { spanish: 'Está cerca / lejos', russian: 'это близко / далеко' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-87.mp3',
        transcript: 'Disculpe, ¿cómo llego al museo? Siga todo recto por esta calle. En el semáforo, gire a la derecha. Camine dos cuadras y el museo está a su izquierda. ¿Está lejos? No, está cerca, a unos 5 minutos caminando. Muchas gracias. De nada, buen día.',
        questions: [
          {
            question: '¿Qué debe hacer en el semáforo?',
            options: ['girar a la izquierda', 'girar a la derecha', 'seguir recto', 'cruzar'],
            correctAnswer: 1,
          },
          {
            question: '¿Está lejos el museo?',
            options: ['sí, muy lejos', 'no, está cerca', 'está a una hora', 'no dice'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Perdone, ¿dónde está la estación?',
          russian: 'Извините, где станция?',
          context: 'Начало вопроса',
        },
        {
          spanish: 'Está a dos cuadras de aquí',
          russian: 'Это в двух кварталах отсюда',
          context: 'Указание расстояния',
        },
        {
          spanish: 'No puedo encontrar mi hotel',
          russian: 'Я не могу найти свой отель',
          context: 'Просьба о помощи',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: false,
      },
    },
    audioUrl: '/audio/a1-87.mp3',
    readingText: 'Para pedir direcciones: ¿Cómo llego a...? ¿Dónde está...? Disculpe/Perdone primero. Direcciones: TODO RECTO (прямо), A LA DERECHA (направо), A LA IZQUIERDA (налево), GIRAR (поворачивать), CRUZAR (переходить). CUADRA/MANZANA = квартал. SEMÁFORO = светофор. Distancia: CERCA (близко), LEJOS (далеко), a X minutos. Siempre agradece: Gracias, Muchas gracias.',
    duration: 29,
    order: 87,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-88',
    levelId: 'a1',
    title: 'Транспорт: Общественный',
    description: 'El transporte público',
    content: {
      introduction: {
        title: 'Transporte público',
        goals: [
          'Выучить виды общественного транспорта',
          'Научиться покупать билеты',
          'Спрашивать о маршрутах',
          'Использовать глаголы движения',
        ],
        overview: 'Общественный транспорт и как им пользоваться.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Transporte público',
        explanation: 'Виды транспорта и как о них говорить',
        examples: [
          { spanish: 'El autobús', russian: 'автобус' },
          { spanish: 'El metro', russian: 'метро' },
          { spanish: 'El tren', russian: 'поезд' },
          { spanish: 'El taxi', russian: 'такси' },
          { spanish: 'El tranvía', russian: 'трамвай' },
          { spanish: 'Tomo el metro para ir al trabajo', russian: 'я езжу на метро на работу' },
          { spanish: 'El autobús número 5', russian: 'автобус номер 5' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-88.mp3',
        transcript: 'Para moverme por la ciudad uso el transporte público. Normalmente tomo el metro porque es rápido. A veces uso el autobús. El taxi es cómodo pero caro. El tren es para viajes largos. Necesito comprar un billete antes de subir.',
        questions: [
          {
            question: '¿Qué transporte usa normalmente?',
            options: ['el taxi', 'el autobús', 'el metro', 'el tren'],
            correctAnswer: 2,
          },
          {
            question: '¿Por qué el taxi no es su preferencia?',
            options: ['es lento', 'es incómodo', 'es caro', 'no hay taxis'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Qué autobús va al centro?',
          russian: 'Какой автобус идет в центр?',
          context: 'Вопрос о маршруте',
        },
        {
          spanish: 'Un billete para el metro, por favor',
          russian: 'Билет на метро, пожалуйста',
          context: 'Покупка билета',
        },
        {
          spanish: 'Voy en metro todos los días',
          russian: 'Я езжу на метро каждый день',
          context: 'О привычках',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-88.mp3',
    readingText: 'El transporte público es esencial. AUTOBÚS (автобус) - económico, con muchas rutas. METRO (метро) - rápido, subterráneo. TREN (поезд) - para distancias largas. TAXI (такси) - cómodo pero caro. TRANVÍA (трамвай) - en algunas ciudades. Verbos: TOMAR/COGER (брать транспорт), SUBIR A (садиться в), BAJAR DE (выходить из). Necesitas BILLETE/BOLETO (билет) o TARJETA (карта).',
    duration: 30,
    order: 88,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-89',
    levelId: 'a1',
    title: 'Транспорт: Личный',
    description: 'El transporte privado',
    content: {
      introduction: {
        title: 'Vehículos privados',
        goals: [
          'Выучить виды личного транспорта',
          'Научиться говорить о вождении',
          'Использовать глаголы conducir, manejar',
          'Говорить о наличии транспорта',
        ],
        overview: 'Личный транспорт и вождение.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Transporte privado',
        explanation: 'Личные транспортные средства',
        examples: [
          { spanish: 'El coche / El carro / El auto', russian: 'машина' },
          { spanish: 'La moto / La motocicleta', russian: 'мотоцикл' },
          { spanish: 'La bicicleta / La bici', russian: 'велосипед' },
          { spanish: 'Conducir / Manejar', russian: 'водить' },
          { spanish: 'Tengo coche', russian: 'у меня есть машина' },
          { spanish: 'Sé conducir', russian: 'я умею водить' },
          { spanish: 'Voy en bici al trabajo', russian: 'я езжу на работу на велосипеде' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-89.mp3',
        transcript: 'Tengo un coche pequeño. Lo uso para ir al supermercado y viajes cortos. Sé conducir desde los 18 años. Mi hermano prefiere la moto - es más rápida en el tráfico. Mi amiga va en bicicleta a todas partes - es saludable y ecológico. Necesitas licencia para conducir coche o moto.',
        questions: [
          {
            question: '¿Qué vehículo tiene la persona?',
            options: ['una moto', 'un coche pequeño', 'una bicicleta', 'nada'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué prefiere el hermano?',
            options: ['el coche', 'la moto', 'la bicicleta', 'el autobús'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Tienes coche?',
          russian: 'У тебя есть машина?',
          context: 'Вопрос о наличии',
        },
        {
          spanish: 'Voy a aprender a conducir',
          russian: 'Я собираюсь научиться водить',
          context: 'О планах',
        },
        {
          spanish: 'Prefiero ir en bicicleta',
          russian: 'Я предпочитаю ездить на велосипеде',
          context: 'О предпочтениях',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: false,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-89.mp3',
    readingText: 'Vehículos privados: COCHE/CARRO/AUTO (машина) - necesitas licencia. MOTO/MOTOCICLETA (мотоцикл) - también necesita licencia. BICICLETA/BICI (велосипед) - no necesita licencia, es ecológica. Verbos: CONDUCIR/MANEJAR (водить), IR EN (ехать на). Expresiones: Tengo coche. Sé conducir. Voy en coche/moto/bici. La LICENCIA DE CONDUCIR (водительские права) es obligatoria para coche y moto.',
    duration: 28,
    order: 89,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-90',
    levelId: 'a1',
    title: 'Распорядок дня: Утро',
    description: 'La rutina de la mañana',
    content: {
      introduction: {
        title: 'Rutina matinal',
        goals: [
          'Выучить действия утренней рутины',
          'Научиться описывать свое утро',
          'Использовать возвратные глаголы',
          'Говорить о времени',
        ],
        overview: 'Утренние действия и рутина.',
      },
      newWords: [],
      grammar: {
        title: 'Verbos reflexivos - rutina',
        explanation: 'Возвратные глаголы для утренней рутины',
        examples: [
          { spanish: 'Me despierto', russian: 'я просыпаюсь' },
          { spanish: 'Me levanto', russian: 'я встаю' },
          { spanish: 'Me ducho', russian: 'я принимаю душ' },
          { spanish: 'Me visto', russian: 'я одеваюсь' },
          { spanish: 'Me peino', russian: 'я причесываюсь' },
          { spanish: 'Me lavo los dientes', russian: 'я чищу зубы' },
          { spanish: 'Desayuno', russian: 'я завтракаю' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-90.mp3',
        transcript: 'Mi rutina de la mañana: Me despierto a las 7. Me quedo en la cama 10 minutos más. Me levanto a las 7:10. Primero me ducho con agua caliente. Después me visto - ropa cómoda para trabajar. Me peino frente al espejo. Me lavo los dientes. Bajo a la cocina y desayuno café con tostadas. Salgo de casa a las 8.',
        questions: [
          {
            question: '¿A qué hora se despierta?',
            options: ['a las 6', 'a las 7', 'a las 8', 'a las 9'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué desayuna?',
            options: ['huevos', 'cereal', 'café con tostadas', 'frutas'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Me levanto temprano',
          russian: 'Я встаю рано',
          context: 'О привычках',
        },
        {
          spanish: 'Tardo una hora en prepararme',
          russian: 'Мне нужен час, чтобы собраться',
          context: 'О времени',
        },
        {
          spanish: 'Siempre desayuno antes de salir',
          russian: 'Я всегда завтракаю перед выходом',
          context: 'О рутине',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-90.mp3',
    readingText: 'La rutina matinal usa muchos verbos reflexivos. DESPERTARSE (просыпаться) - suena el despertador. LEVANTARSE (вставать) - salir de la cama. DUCHARSE/BAÑARSE (принимать душ/ванну). VESTIRSE (одеваться). PEINARSE (причесываться). LAVARSE los dientes/la cara (умываться). MAQUILLARSE (краситься - para mujeres). AFEITARSE (бриться - para hombres). Después: DESAYUNAR y SALIR de casa.',
    duration: 29,
    order: 90,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-91',
    levelId: 'a1',
    title: 'Распорядок дня: День',
    description: 'Actividades del día',
    content: {
      introduction: {
        title: 'Rutina diaria',
        goals: [
          'Выучить дневные активности',
          'Научиться говорить о работе/учебе',
          'Использовать выражения времени',
          'Описывать типичный день',
        ],
        overview: 'Дневные дела и активности.',
      },
      newWords: [],
      grammar: {
        title: 'Actividades diarias',
        explanation: 'Что делаем в течение дня',
        examples: [
          { spanish: 'Trabajo de 9 a 5', russian: 'я работаю с 9 до 5' },
          { spanish: 'Estudio en la universidad', russian: 'я учусь в университете' },
          { spanish: 'Como a las 2', russian: 'я обедаю в 2' },
          { spanish: 'Tengo una reunión', russian: 'у меня встреча' },
          { spanish: 'Hago ejercicio', russian: 'я занимаюсь спортом' },
          { spanish: 'Voy de compras', russian: 'я иду по магазинам' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-91.mp3',
        transcript: 'Mi día típico: Llego a la oficina a las 9. Trabajo en mi computadora hasta las 2. A las 2 como con mis colegas en un restaurante cerca. Por la tarde tengo reuniones. A las 5 termino mi trabajo. Voy al gimnasio a hacer ejercicio. Después paso por el supermercado a comprar comida.',
        questions: [
          {
            question: '¿A qué hora llega a la oficina?',
            options: ['a las 8', 'a las 9', 'a las 10', 'a las 11'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué hace después del trabajo?',
            options: ['va a casa', 'va al gimnasio', 'va al cine', 'va a dormir'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Tengo mucho trabajo hoy',
          russian: 'У меня сегодня много работы',
          context: 'О занятости',
        },
        {
          spanish: 'Después del trabajo voy al cine',
          russian: 'После работы иду в кино',
          context: 'О планах',
        },
        {
          spanish: 'Mi día es muy ocupado',
          russian: 'Мой день очень занятой',
          context: 'Описание дня',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: false,
      },
    },
    audioUrl: '/audio/a1-91.mp3',
    readingText: 'Durante el día hacemos muchas actividades. TRABAJAR (работать) - en oficina, tienda, etc. ESTUDIAR (учиться) - en escuela, universidad. COMER (обедать) - comida del mediodía. TENER REUNIONES (иметь встречи). HACER EJERCICIO (заниматься спортом). IR DE COMPRAS (ходить по магазинам). Expresiones de tiempo: por la mañana, al mediodía, por la tarde, después de..., antes de...',
    duration: 27,
    order: 91,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-92',
    levelId: 'a1',
    title: 'Распорядок дня: Вечер',
    description: 'La rutina de la noche',
    content: {
      introduction: {
        title: 'Rutina nocturna',
        goals: [
          'Выучить вечерние активности',
          'Научиться говорить о вечере',
          'Описывать отдых и хобби',
          'Использовать глаголы релаксации',
        ],
        overview: 'Вечерняя рутина и отдых.',
      },
      newWords: [],
      grammar: {
        title: 'Actividades nocturnas',
        explanation: 'Что делаем вечером',
        examples: [
          { spanish: 'Llego a casa', russian: 'я прихожу домой' },
          { spanish: 'Ceno a las 9', russian: 'я ужинаю в 9' },
          { spanish: 'Veo la televisión', russian: 'я смотрю телевизор' },
          { spanish: 'Leo un libro', russian: 'я читаю книгу' },
          { spanish: 'Descanso en el sofá', russian: 'я отдыхаю на диване' },
          { spanish: 'Me acuesto a las 11', russian: 'я ложусь спать в 11' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-92.mp3',
        transcript: 'Por la noche, después del trabajo, llego a casa cansado. Primero me cambio de ropa - me pongo algo cómodo. Preparo la cena, normalmente algo rápido. Ceno mientras veo las noticias en la televisión. Después leo un libro o navego por internet. Hablo con mi familia por teléfono. Me acuesto a las 11 porque mañana me levanto temprano.',
        questions: [
          {
            question: '¿Qué hace mientras cena?',
            options: ['lee', 've las noticias', 'habla por teléfono', 'navega por internet'],
            correctAnswer: 1,
          },
          {
            question: '¿A qué hora se acuesta?',
            options: ['a las 9', 'a las 10', 'a las 11', 'a las 12'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: 'Por la noche me relajo',
          russian: 'Вечером я расслабляюсь',
          context: 'О привычках',
        },
        {
          spanish: 'Ceno en familia',
          russian: 'Я ужинаю с семьей',
          context: 'О традициях',
        },
        {
          spanish: 'Me gusta leer antes de dormir',
          russian: 'Мне нравится читать перед сном',
          context: 'О предпочтениях',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-92.mp3',
    readingText: 'La rutina nocturna es para relajarse. LLEGAR A CASA (приходить домой). CAMBIARSE DE ROPA (переодеваться). CENAR (ужинать) - más tarde que en otros países. VER LA TELEVISIÓN (смотреть ТВ). LEER (читать). ESCUCHAR MÚSICA (слушать музыку). NAVEGAR POR INTERNET (сидеть в интернете). HABLAR POR TELÉFONO (говорить по телефону). ACOSTARSE (ложиться спать). DORMIR (спать).',
    duration: 30,
    order: 92,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-93',
    levelId: 'a1',
    title: 'Дни недели',
    description: 'Los días de la semana',
    content: {
      introduction: {
        title: 'Los días de la semana',
        goals: [
          'Выучить все дни недели',
          'Научиться говорить о планах на неделю',
          'Использовать артикли с днями',
          'Практиковать расписание',
        ],
        overview: 'Дни недели и как их использовать.',
      },
      newWords: [],
      grammar: {
        title: 'Los días',
        explanation: 'Дни недели и артикли',
        examples: [
          { spanish: 'Lunes', russian: 'понедельник' },
          { spanish: 'Martes', russian: 'вторник' },
          { spanish: 'Miércoles', russian: 'среда' },
          { spanish: 'Jueves', russian: 'четверг' },
          { spanish: 'Viernes', russian: 'пятница' },
          { spanish: 'Sábado', russian: 'суббота' },
          { spanish: 'Domingo', russian: 'воскресенье' },
          { spanish: 'El lunes voy al gimnasio', russian: 'в понедельник я иду в спортзал' },
          { spanish: 'Los lunes trabajo', russian: 'по понедельникам я работаю' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-93.mp3',
        transcript: 'Mi semana: El lunes y el miércoles voy al gimnasio. Los martes tengo clase de español. El jueves ceno con amigos. El viernes salgo del trabajo temprano. El sábado hago las compras. El domingo descanso y visito a mi familia. El fin de semana es mi tiempo favorito.',
        questions: [
          {
            question: '¿Qué hace los martes?',
            options: ['va al gimnasio', 'tiene clase de español', 'cena con amigos', 'descansa'],
            correctAnswer: 1,
          },
          {
            question: '¿Cuándo visita a la familia?',
            options: ['el viernes', 'el sábado', 'el domingo', 'el lunes'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Qué haces el sábado?',
          russian: 'Что ты делаешь в субботу?',
          context: 'Вопрос о планах',
        },
        {
          spanish: 'Los domingos duermo hasta tarde',
          russian: 'По воскресеньям я сплю допоздна',
          context: 'О привычках',
        },
        {
          spanish: 'El fin de semana voy al cine',
          russian: 'В выходные я иду в кино',
          context: 'О досуге',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: false,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-93.mp3',
    readingText: 'Los días de la semana en español: LUNES, MARTES, MIÉRCOLES, JUEVES, VIERNES (días laborables). SÁBADO, DOMINGO (fin de semana). Importante: en español los días NO se escriben con mayúscula. Artículos: EL lunes (en un lunes específico), LOS lunes (todos los lunes, habitualmente). FIN DE SEMANA = выходные. Los días no tienen género específico, siempre usan artículo masculino.',
    duration: 28,
    order: 93,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-94',
    levelId: 'a1',
    title: 'Месяцы года',
    description: 'Los meses del año',
    content: {
      introduction: {
        title: 'Los meses',
        goals: [
          'Выучить все месяцы',
          'Научиться говорить о датах',
          'Использовать предлог EN с месяцами',
          'Связывать месяцы с сезонами',
        ],
        overview: 'Месяцы года и даты.',
      },
      newWords: [],
      grammar: {
        title: 'Los meses del año',
        explanation: 'Месяцы и как их использовать',
        examples: [
          { spanish: 'Enero, Febrero, Marzo', russian: 'январь, февраль, март' },
          { spanish: 'Abril, Mayo, Junio', russian: 'апрель, май, июнь' },
          { spanish: 'Julio, Agosto, Septiembre', russian: 'июль, август, сентябрь' },
          { spanish: 'Octubre, Noviembre, Diciembre', russian: 'октябрь, ноябрь, декабрь' },
          { spanish: 'En enero hace frío', russian: 'в январе холодно' },
          { spanish: 'Nací en mayo', russian: 'я родился в мае' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-94.mp3',
        transcript: 'El año tiene doce meses. En enero y febrero hace frío - es invierno. Marzo, abril y mayo son primavera. Junio, julio y agosto son verano - hace calor. Septiembre, octubre y noviembre son otoño. Diciembre es invierno otra vez. Mi cumpleaños es en abril. ¿En qué mes naciste?',
        questions: [
          {
            question: '¿Cuándo es primavera?',
            options: ['enero-marzo', 'marzo-mayo', 'junio-agosto', 'septiembre-noviembre'],
            correctAnswer: 1,
          },
          {
            question: '¿Cuándo es el cumpleaños de la persona?',
            options: ['en marzo', 'en abril', 'en mayo', 'en junio'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿En qué mes naciste?',
          russian: 'В каком месяце ты родился?',
          context: 'Вопрос о дне рождения',
        },
        {
          spanish: 'En julio voy de vacaciones',
          russian: 'В июле я еду в отпуск',
          context: 'О планах',
        },
        {
          spanish: 'Mi mes favorito es septiembre',
          russian: 'Мой любимый месяц - сентябрь',
          context: 'О предпочтениях',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-94.mp3',
    readingText: 'Los doce meses: ENERO, FEBRERO, MARZO (invierno/primavera). ABRIL, MAYO, JUNIO (primavera/verano). JULIO, AGOSTO, SEPTIEMBRE (verano/otoño). OCTUBRE, NOVIEMBRE, DICIEMBRE (otoño/invierno). Como los días, los meses NO se escriben con mayúscula en español. Usamos EN con meses: en enero, en mayo. Para fechas completas: Nací el 15 de mayo de 1990.',
    duration: 29,
    order: 94,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-95',
    levelId: 'a1',
    title: 'Погода: Описание',
    description: 'El tiempo y el clima',
    content: {
      introduction: {
        title: 'Hablando del tiempo',
        goals: [
          'Выучить слова о погоде',
          'Научиться описывать погоду',
          'Использовать безличные конструкции',
          'Говорить о сезонах',
        ],
        overview: 'Как говорить о погоде и климате.',
      },
      newWords: [],
      grammar: {
        title: 'Expresiones del tiempo',
        explanation: 'Безличные конструкции HACE, HAY, ESTÁ',
        examples: [
          { spanish: 'Hace calor', russian: 'жарко' },
          { spanish: 'Hace frío', russian: 'холодно' },
          { spanish: 'Hace sol', russian: 'солнечно' },
          { spanish: 'Hace viento', russian: 'ветрено' },
          { spanish: 'Llueve', russian: 'идет дождь' },
          { spanish: 'Nieva', russian: 'идет снег' },
          { spanish: 'Está nublado', russian: 'облачно' },
          { spanish: 'Hay tormenta', russian: 'гроза' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-95.mp3',
        transcript: 'Hoy hace buen tiempo. Hace sol y la temperatura es agradable. No hace ni frío ni calor. Ayer llovió todo el día. Mañana dicen que hará viento. En invierno nieva mucho aquí. En verano hace mucho calor. La primavera y el otoño tienen el mejor clima.',
        questions: [
          {
            question: '¿Cómo está el tiempo hoy?',
            options: ['llueve', 'nieva', 'hace sol', 'hace frío'],
            correctAnswer: 2,
          },
          {
            question: '¿Qué pasó ayer?',
            options: ['hizo sol', 'llovió', 'nevó', 'hizo viento'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Qué tiempo hace hoy?',
          russian: 'Какая сегодня погода?',
          context: 'Вопрос о погоде',
        },
        {
          spanish: 'Hace un frío terrible',
          russian: 'Ужасно холодно',
          context: 'Жалоба на погоду',
        },
        {
          spanish: 'Parece que va a llover',
          russian: 'Похоже, будет дождь',
          context: 'Прогноз',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: false,
      },
    },
    audioUrl: '/audio/a1-95.mp3',
    readingText: 'Para hablar del tiempo usamos construcciones especiales. HACE + sustantivo: hace calor/frío/sol/viento/buen tiempo/mal tiempo. Verbos: LLOVER (llove), NEVAR (nieva), GRANIZAR (graniza). ESTÁ + adjetivo: está nublado, está despejado. HAY + sustantivo: hay tormenta, hay niebla. Temperatura: grados (градусы) - Hace 20 grados. El clima varía según la estación.',
    duration: 30,
    order: 95,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-96',
    levelId: 'a1',
    title: 'Сезоны года',
    description: 'Las estaciones del año',
    content: {
      introduction: {
        title: 'Las cuatro estaciones',
        goals: [
          'Выучить названия сезонов',
          'Научиться описывать каждый сезон',
          'Связывать сезоны с активностями',
          'Говорить о предпочтениях',
        ],
        overview: 'Четыре сезона и их характеристики.',
      },
      newWords: [],
      grammar: {
        title: 'Las estaciones',
        explanation: 'Сезоны и их описания',
        examples: [
          { spanish: 'La primavera', russian: 'весна' },
          { spanish: 'El verano', russian: 'лето' },
          { spanish: 'El otoño', russian: 'осень' },
          { spanish: 'El invierno', russian: 'зима' },
          { spanish: 'En primavera florecen las flores', russian: 'весной цветут цветы' },
          { spanish: 'En verano voy a la playa', russian: 'летом я хожу на пляж' },
          { spanish: 'En otoño caen las hojas', russian: 'осенью падают листья' },
          { spanish: 'En invierno nieva', russian: 'зимой идет снег' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-96.mp3',
        transcript: 'Las cuatro estaciones son muy diferentes. La primavera es bonita - todo florece y hace buen tiempo. El verano es caluroso - vamos a la playa y tomamos el sol. El otoño es tranquilo - los árboles cambian de color. El invierno es frío - nieva y usamos ropa de abrigo. Mi estación favorita es la primavera.',
        questions: [
          {
            question: '¿Cuándo hace calor?',
            options: ['en primavera', 'en verano', 'en otoño', 'en invierno'],
            correctAnswer: 1,
          },
          {
            question: '¿Cuál es su estación favorita?',
            options: ['primavera', 'verano', 'otoño', 'invierno'],
            correctAnswer: 0,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Cuál es tu estación favorita?',
          russian: 'Какое твое любимое время года?',
          context: 'Вопрос о предпочтениях',
        },
        {
          spanish: 'Me encanta el verano',
          russian: 'Я обожаю лето',
          context: 'О предпочтениях',
        },
        {
          spanish: 'En invierno esquío en las montañas',
          russian: 'Зимой я катаюсь на лыжах в горах',
          context: 'О хобби',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-96.mp3',
    readingText: 'Las cuatro estaciones: PRIMAVERA (март-май) - flores, clima templado. VERANO (июнь-август) - calor, playa, vacaciones. OTOÑO (сентябрь-ноябрь) - hojas caen, clima fresco. INVIERNO (декабрь-февраль) - frío, nieve, Navidad. Actividades: En primavera - pasear. En verano - nadar. En otoño - caminar en parques. En invierno - esquiar. ¿Cuál prefieres?',
    duration: 28,
    order: 96,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-97',
    levelId: 'a1',
    title: 'Время: Часы и минуты',
    description: '¿Qué hora es?',
    content: {
      introduction: {
        title: 'Decir la hora',
        goals: [
          'Научиться спрашивать о времени',
          'Выучить как говорить время',
          'Понять систему 24 часов',
          'Использовать y/menos',
        ],
        overview: 'Как спрашивать и говорить время.',
      },
      newWords: [],
      grammar: {
        title: '¿Qué hora es?',
        explanation: 'Система времени в испанском',
        examples: [
          { spanish: '¿Qué hora es?', russian: 'который час?' },
          { spanish: 'Es la una', russian: 'час (13:00)' },
          { spanish: 'Son las dos', russian: 'два часа' },
          { spanish: 'Son las tres y cuarto', russian: 'три пятнадцать' },
          { spanish: 'Son las cuatro y media', russian: 'половина пятого' },
          { spanish: 'Son las cinco menos cuarto', russian: 'без пятнадцати пять' },
          { spanish: 'Es mediodía / Es medianoche', russian: 'полдень / полночь' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-97.mp3',
        transcript: '¿Qué hora es? Son las tres y media de la tarde. ¿A qué hora comes? Como a las dos. ¿A qué hora empieza la película? Empieza a las siete y cuarto. ¿Tienes hora? Sí, son las cinco menos diez. El tren sale a las nueve en punto.',
        questions: [
          {
            question: '¿Qué hora es cuando preguntan?',
            options: ['las dos', 'las tres y media', 'las cinco', 'las siete'],
            correctAnswer: 1,
          },
          {
            question: '¿A qué hora empieza la película?',
            options: ['a las seis', 'a las siete', 'a las siete y cuarto', 'a las ocho'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿A qué hora quedamos?',
          russian: 'Во сколько встречаемся?',
          context: 'Планирование встречи',
        },
        {
          spanish: 'Son las ocho en punto',
          russian: 'Ровно восемь',
          context: 'Точное время',
        },
        {
          spanish: 'Llego en media hora',
          russian: 'Приду через полчаса',
          context: 'О прибытии',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: false,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-97.mp3',
    readingText: 'Para preguntar: ¿QUÉ HORA ES? Para 1: ES LA UNA. Para 2-12: SON LAS + número. Y = и (dos y diez = 2:10). MENOS = без (tres menos cinco = 2:55). Y CUARTO = и пятнадцать. Y MEDIA = и тридцать. MENOS CUARTO = без пятнадцати. EN PUNTO = ровно. MEDIODÍA = полдень (12:00). MEDIANOCHE = полночь (00:00). ¿A QUÉ HORA? = во сколько?',
    duration: 31,
    order: 97,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-98',
    levelId: 'a1',
    title: 'Хобби и свободное время',
    description: 'Pasatiempos y tiempo libre',
    content: {
      introduction: {
        title: 'Hobbies y ocio',
        goals: [
          'Выучить названия хобби',
          'Научиться говорить о досуге',
          'Использовать глаголы интересов',
          'Обсуждать предпочтения',
        ],
        overview: 'Как говорить о хобби и свободном времени.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Pasatiempos',
        explanation: 'Хобби и глаголы',
        examples: [
          { spanish: 'Leer libros', russian: 'читать книги' },
          { spanish: 'Ver películas', russian: 'смотреть фильмы' },
          { spanish: 'Escuchar música', russian: 'слушать музыку' },
          { spanish: 'Hacer deporte', russian: 'заниматься спортом' },
          { spanish: 'Viajar', russian: 'путешествовать' },
          { spanish: 'Tocar un instrumento', russian: 'играть на инструменте' },
          { spanish: 'Pintar / Dibujar', russian: 'рисовать' },
          { spanish: 'Cocinar', russian: 'готовить' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-98.mp3',
        transcript: 'En mi tiempo libre me gusta leer libros, especialmente novelas. También me encanta ver películas en el cine. Los fines de semana hago deporte - juego al fútbol con amigos. Mi hermana toca la guitarra. Mi padre cocina como hobby. Viajar es mi pasión - visito un país nuevo cada año.',
        questions: [
          {
            question: '¿Qué le gusta hacer a la persona?',
            options: ['solo leer', 'leer y ver películas', 'solo cocinar', 'solo viajar'],
            correctAnswer: 1,
          },
          {
            question: '¿Qué toca la hermana?',
            options: ['el piano', 'la guitarra', 'el violín', 'nada'],
            correctAnswer: 1,
          },
        ],
      },
      phrases: [
        {
          spanish: '¿Qué haces en tu tiempo libre?',
          russian: 'Что ты делаешь в свободное время?',
          context: 'Вопрос о хобби',
        },
        {
          spanish: 'Mi hobby es la fotografía',
          russian: 'Мое хобби - фотография',
          context: 'О своих интересах',
        },
        {
          spanish: 'Me gusta salir con amigos',
          russian: 'Мне нравится гулять с друзьями',
          context: 'О досуге',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-98.mp3',
    readingText: 'Pasatiempos comunes: LEER (читать) - libros, revistas. VER (смотреть) - películas, series. ESCUCHAR (слушать) - música, podcasts. HACER DEPORTE (заниматься спортом) - fútbol, tenis, natación. VIAJAR (путешествовать). TOCAR un instrumento (играть на инструменте) - guitarra, piano. PINTAR/DIBUJAR (рисовать). COCINAR (готовить). BAILAR (танцевать). JUGAR videojuegos (играть в видеоигры). ¿Cuál es tu hobby?',
    duration: 32,
    order: 98,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-99',
    levelId: 'a1',
    title: 'Праздники и традиции',
    description: 'Fiestas y celebraciones',
    content: {
      introduction: {
        title: 'Días festivos',
        goals: [
          'Выучить основные праздники',
          'Научиться говорить о традициях',
          'Использовать глагол CELEBRAR',
          'Понять культурные особенности',
        ],
        overview: 'Праздники испаноязычного мира.',
      },
      newWords: [],
      grammar: {
        title: 'Vocabulario: Fiestas',
        explanation: 'Праздники и традиции',
        examples: [
          { spanish: 'La Navidad', russian: 'Рождество' },
          { spanish: 'El Año Nuevo', russian: 'Новый год' },
          { spanish: 'La Semana Santa', russian: 'Страстная неделя' },
          { spanish: 'El cumpleaños', russian: 'день рождения' },
          { spanish: 'El Día de los Reyes Magos', russian: 'День трех королей' },
          { spanish: 'Celebramos en familia', russian: 'мы празднуем в семье' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-99.mp3',
        transcript: 'Mi fiesta favorita es la Navidad. Celebramos el 24 de diciembre con una cena especial. En España, los niños reciben regalos el 6 de enero, en el Día de Reyes. El Año Nuevo lo celebramos con las doce uvas de la suerte. Mi cumpleaños es en mayo - hago una fiesta con amigos. La Semana Santa es importante en mi ciudad.',
        questions: [
          {
            question: '¿Cuándo es la cena de Navidad?',
            options: ['el 24 de diciembre', 'el 25 de diciembre', 'el 31 de diciembre', 'el 6 de enero'],
            correctAnswer: 0,
          },
          {
            question: '¿Cuándo reciben regalos los niños en España?',
            options: ['en Navidad', 'en Año Nuevo', 'el 6 de enero', 'en cumpleaños'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: '¡Feliz Navidad!',
          russian: 'Счастливого Рождества!',
          context: 'Поздравление',
        },
        {
          spanish: '¿Cómo celebras tu cumpleaños?',
          russian: 'Как ты празднуешь свой день рождения?',
          context: 'Вопрос о традициях',
        },
        {
          spanish: 'Las fiestas son momentos especiales',
          russian: 'Праздники - особенные моменты',
          context: 'Общее высказывание',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: false,
      },
    },
    audioUrl: '/audio/a1-99.mp3',
    readingText: 'Fiestas importantes: NAVIDAD (25 diciembre) - celebración religiosa y familiar. AÑO NUEVO (31 diciembre/1 enero) - con las 12 uvas. REYES MAGOS (6 enero) - regalos para niños en España. SEMANA SANTA (marzo/abril) - procesiones religiosas. DÍA DE LOS MUERTOS (2 noviembre) - en México. CUMPLEAÑOS - fiesta personal. Verbo CELEBRAR: Celebro mi cumpleaños. Celebramos la Navidad.',
    duration: 29,
    order: 99,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'a1-100',
    levelId: 'a1',
    title: 'Итоговая практика A1: Полный обзор',
    description: 'Repaso completo del nivel A1',
    content: {
      introduction: {
        title: 'Repaso final A1',
        goals: [
          'Повторить всю грамматику A1',
          'Практиковать всю лексику',
          'Объединить все темы',
          'Подготовиться к уровню A2',
        ],
        overview: 'Финальный урок - обзор всего изученного на уровне A1.',
      },
      newWords: [],
      grammar: {
        title: 'Repaso general A1',
        explanation: 'Все темы уровня A1 вместе',
        examples: [
          { spanish: 'Me llamo Ana y tengo 25 años', russian: 'меня зовут Ана и мне 25 лет' },
          { spanish: 'Vivo en Madrid con mi familia', russian: 'я живу в Мадриде с моей семьей' },
          { spanish: 'Trabajo como profesora de español', russian: 'я работаю учителем испанского' },
          { spanish: 'Me gusta leer, viajar y cocinar', russian: 'мне нравится читать, путешествовать и готовить' },
          { spanish: 'Los fines de semana voy al cine', russian: 'по выходным я хожу в кино' },
          { spanish: 'Hablo español e inglés', russian: 'я говорю по-испански и по-английски' },
        ],
      },
      listening: {
        audioUrl: '/audio/a1-100.mp3',
        transcript: 'Hola, me llamo Carlos. Soy de México pero vivo en España desde hace dos años. Tengo 30 años y trabajo en una oficina en el centro de Madrid. Mi familia está en México - tengo dos hermanos y mis padres. Vivo en un apartamento pequeño pero cómodo. Todos los días me levanto a las 7, desayuno café con tostadas y voy al trabajo en metro. Trabajo de 9 a 6. Después del trabajo voy al gimnasio o me encuentro con amigos. Los fines de semana me gusta viajar por España. Hablo español, inglés y un poco de francés. Me encanta la cultura española - la comida, las fiestas, la gente. En mi tiempo libre leo libros y veo películas. Mi sueño es viajar por toda Latinoamérica algún día.',
        questions: [
          {
            question: '¿De dónde es Carlos?',
            options: ['de España', 'de México', 'de Argentina', 'de Colombia'],
            correctAnswer: 1,
          },
          {
            question: '¿Cómo va al trabajo?',
            options: ['en coche', 'en autobús', 'en metro', 'a pie'],
            correctAnswer: 2,
          },
          {
            question: '¿Qué hace los fines de semana?',
            options: ['trabaja', 'estudia', 'viaja por España', 'duerme'],
            correctAnswer: 2,
          },
        ],
      },
      phrases: [
        {
          spanish: '¡Felicidades! Has completado el nivel A1',
          russian: 'Поздравляю! Ты завершил уровень A1',
          context: 'Завершение',
        },
        {
          spanish: 'Ahora puedo comunicarme en situaciones básicas',
          russian: 'Теперь я могу общаться в базовых ситуациях',
          context: 'Достижение',
        },
        {
          spanish: 'Estoy listo para el nivel A2',
          russian: 'Я готов к уровню A2',
          context: 'Следующий шаг',
        },
      },
      homework: {
        vocabularyTest: true,
        listening: true,
        reading: true,
        writing: true,
      },
    },
    audioUrl: '/audio/a1-100.mp3',
    readingText: '¡Felicidades! Has completado el nivel A1 de español. Ahora sabes: presentarte, hablar de tu familia, describir tu casa, pedir comida en restaurantes, preguntar direcciones, hablar del tiempo, describir tu rutina diaria, hablar de tus hobbies, usar el presente de indicativo, hacer preguntas, usar posesivos. Puedes comunicarte en situaciones cotidianas básicas. El siguiente paso es el nivel A2, donde aprenderás tiempos pasados, futuro y mucho más vocabulario. ¡Sigue practicando!',
    duration: 35,
    order: 100,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
]
