import { Lesson } from '@/types'

// C1 Lessons: Futuro Perfecto (Lessons 21-40)
export const c1LessonsFuturoPerfecto: Lesson[] = [
  {
    id: 'c1-21',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 1',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 1',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 1', russian: 'Пример 1' },
          { spanish: 'Frase práctica 1', russian: 'Практическая фраза 1' },
          { spanish: 'Contexto real 1', russian: 'Реальный контекст 1' },
          { spanish: 'Aplicación 1', russian: 'Применение 1' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-21.mp3',
        transcript: 'Este es el texto de práctica para el audio 1. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 1', russian: 'Полезная фраза 1', context: 'Contexto diario' },
        { spanish: 'Expresión común 1', russian: 'Обычное выражение 1', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: false, writing: false },
    },
    audioUrl: '/audio/c1-21.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 29,
    order: 21,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-22',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 2',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 2',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 2', russian: 'Пример 2' },
          { spanish: 'Frase práctica 2', russian: 'Практическая фраза 2' },
          { spanish: 'Contexto real 2', russian: 'Реальный контекст 2' },
          { spanish: 'Aplicación 2', russian: 'Применение 2' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-22.mp3',
        transcript: 'Este es el texto de práctica para el audio 2. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 2', russian: 'Полезная фраза 2', context: 'Contexto diario' },
        { spanish: 'Expresión común 2', russian: 'Обычное выражение 2', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: true, writing: false },
    },
    audioUrl: '/audio/c1-22.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 30,
    order: 22,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-23',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 3',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 3',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 3', russian: 'Пример 3' },
          { spanish: 'Frase práctica 3', russian: 'Практическая фраза 3' },
          { spanish: 'Contexto real 3', russian: 'Реальный контекст 3' },
          { spanish: 'Aplicación 3', russian: 'Применение 3' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-23.mp3',
        transcript: 'Este es el texto de práctica para el audio 3. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 3', russian: 'Полезная фраза 3', context: 'Contexto diario' },
        { spanish: 'Expresión común 3', russian: 'Обычное выражение 3', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: false, writing: true },
    },
    audioUrl: '/audio/c1-23.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 31,
    order: 23,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-24',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 4',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 4',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 4', russian: 'Пример 4' },
          { spanish: 'Frase práctica 4', russian: 'Практическая фраза 4' },
          { spanish: 'Contexto real 4', russian: 'Реальный контекст 4' },
          { spanish: 'Aplicación 4', russian: 'Применение 4' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-24.mp3',
        transcript: 'Este es el texto de práctica para el audio 4. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 4', russian: 'Полезная фраза 4', context: 'Contexto diario' },
        { spanish: 'Expresión común 4', russian: 'Обычное выражение 4', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: true, writing: false },
    },
    audioUrl: '/audio/c1-24.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 32,
    order: 24,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-25',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 5',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 5',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 5', russian: 'Пример 5' },
          { spanish: 'Frase práctica 5', russian: 'Практическая фраза 5' },
          { spanish: 'Contexto real 5', russian: 'Реальный контекст 5' },
          { spanish: 'Aplicación 5', russian: 'Применение 5' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-25.mp3',
        transcript: 'Este es el texto de práctica para el audio 5. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 5', russian: 'Полезная фраза 5', context: 'Contexto diario' },
        { spanish: 'Expresión común 5', russian: 'Обычное выражение 5', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: false, writing: false },
    },
    audioUrl: '/audio/c1-25.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 33,
    order: 25,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-26',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 6',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 6',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 6', russian: 'Пример 6' },
          { spanish: 'Frase práctica 6', russian: 'Практическая фраза 6' },
          { spanish: 'Contexto real 6', russian: 'Реальный контекст 6' },
          { spanish: 'Aplicación 6', russian: 'Применение 6' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-26.mp3',
        transcript: 'Este es el texto de práctica para el audio 6. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 6', russian: 'Полезная фраза 6', context: 'Contexto diario' },
        { spanish: 'Expresión común 6', russian: 'Обычное выражение 6', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: true, writing: true },
    },
    audioUrl: '/audio/c1-26.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 34,
    order: 26,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-27',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 7',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 7',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 7', russian: 'Пример 7' },
          { spanish: 'Frase práctica 7', russian: 'Практическая фраза 7' },
          { spanish: 'Contexto real 7', russian: 'Реальный контекст 7' },
          { spanish: 'Aplicación 7', russian: 'Применение 7' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-27.mp3',
        transcript: 'Este es el texto de práctica para el audio 7. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 7', russian: 'Полезная фраза 7', context: 'Contexto diario' },
        { spanish: 'Expresión común 7', russian: 'Обычное выражение 7', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: false, writing: false },
    },
    audioUrl: '/audio/c1-27.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 35,
    order: 27,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-28',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 8',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 8',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 8', russian: 'Пример 8' },
          { spanish: 'Frase práctica 8', russian: 'Практическая фраза 8' },
          { spanish: 'Contexto real 8', russian: 'Реальный контекст 8' },
          { spanish: 'Aplicación 8', russian: 'Применение 8' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-28.mp3',
        transcript: 'Este es el texto de práctica para el audio 8. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 8', russian: 'Полезная фраза 8', context: 'Contexto diario' },
        { spanish: 'Expresión común 8', russian: 'Обычное выражение 8', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: true, writing: false },
    },
    audioUrl: '/audio/c1-28.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 36,
    order: 28,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-29',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 9',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 9',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 9', russian: 'Пример 9' },
          { spanish: 'Frase práctica 9', russian: 'Практическая фраза 9' },
          { spanish: 'Contexto real 9', russian: 'Реальный контекст 9' },
          { spanish: 'Aplicación 9', russian: 'Применение 9' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-29.mp3',
        transcript: 'Este es el texto de práctica para el audio 9. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 9', russian: 'Полезная фраза 9', context: 'Contexto diario' },
        { spanish: 'Expresión común 9', russian: 'Обычное выражение 9', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: false, writing: true },
    },
    audioUrl: '/audio/c1-29.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 37,
    order: 29,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-30',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 10',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 10',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 10', russian: 'Пример 10' },
          { spanish: 'Frase práctica 10', russian: 'Практическая фраза 10' },
          { spanish: 'Contexto real 10', russian: 'Реальный контекст 10' },
          { spanish: 'Aplicación 10', russian: 'Применение 10' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-30.mp3',
        transcript: 'Este es el texto de práctica para el audio 10. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 10', russian: 'Полезная фраза 10', context: 'Contexto diario' },
        { spanish: 'Expresión común 10', russian: 'Обычное выражение 10', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: true, writing: false },
    },
    audioUrl: '/audio/c1-30.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 28,
    order: 30,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-31',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 11',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 11',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 11', russian: 'Пример 11' },
          { spanish: 'Frase práctica 11', russian: 'Практическая фраза 11' },
          { spanish: 'Contexto real 11', russian: 'Реальный контекст 11' },
          { spanish: 'Aplicación 11', russian: 'Применение 11' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-31.mp3',
        transcript: 'Este es el texto de práctica para el audio 11. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 11', russian: 'Полезная фраза 11', context: 'Contexto diario' },
        { spanish: 'Expresión común 11', russian: 'Обычное выражение 11', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: false, writing: false },
    },
    audioUrl: '/audio/c1-31.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 29,
    order: 31,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-32',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 12',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 12',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 12', russian: 'Пример 12' },
          { spanish: 'Frase práctica 12', russian: 'Практическая фраза 12' },
          { spanish: 'Contexto real 12', russian: 'Реальный контекст 12' },
          { spanish: 'Aplicación 12', russian: 'Применение 12' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-32.mp3',
        transcript: 'Este es el texto de práctica para el audio 12. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 12', russian: 'Полезная фраза 12', context: 'Contexto diario' },
        { spanish: 'Expresión común 12', russian: 'Обычное выражение 12', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: true, writing: true },
    },
    audioUrl: '/audio/c1-32.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 30,
    order: 32,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-33',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 13',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 13',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 13', russian: 'Пример 13' },
          { spanish: 'Frase práctica 13', russian: 'Практическая фраза 13' },
          { spanish: 'Contexto real 13', russian: 'Реальный контекст 13' },
          { spanish: 'Aplicación 13', russian: 'Применение 13' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-33.mp3',
        transcript: 'Este es el texto de práctica para el audio 13. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 13', russian: 'Полезная фраза 13', context: 'Contexto diario' },
        { spanish: 'Expresión común 13', russian: 'Обычное выражение 13', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: false, writing: false },
    },
    audioUrl: '/audio/c1-33.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 31,
    order: 33,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-34',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 14',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 14',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 14', russian: 'Пример 14' },
          { spanish: 'Frase práctica 14', russian: 'Практическая фраза 14' },
          { spanish: 'Contexto real 14', russian: 'Реальный контекст 14' },
          { spanish: 'Aplicación 14', russian: 'Применение 14' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-34.mp3',
        transcript: 'Este es el texto de práctica para el audio 14. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 14', russian: 'Полезная фраза 14', context: 'Contexto diario' },
        { spanish: 'Expresión común 14', russian: 'Обычное выражение 14', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: true, writing: false },
    },
    audioUrl: '/audio/c1-34.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 32,
    order: 34,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-35',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 15',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 15',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 15', russian: 'Пример 15' },
          { spanish: 'Frase práctica 15', russian: 'Практическая фраза 15' },
          { spanish: 'Contexto real 15', russian: 'Реальный контекст 15' },
          { spanish: 'Aplicación 15', russian: 'Применение 15' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-35.mp3',
        transcript: 'Este es el texto de práctica para el audio 15. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 15', russian: 'Полезная фраза 15', context: 'Contexto diario' },
        { spanish: 'Expresión común 15', russian: 'Обычное выражение 15', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: false, writing: true },
    },
    audioUrl: '/audio/c1-35.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 33,
    order: 35,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-36',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 16',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 16',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 16', russian: 'Пример 16' },
          { spanish: 'Frase práctica 16', russian: 'Практическая фраза 16' },
          { spanish: 'Contexto real 16', russian: 'Реальный контекст 16' },
          { spanish: 'Aplicación 16', russian: 'Применение 16' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-36.mp3',
        transcript: 'Este es el texto de práctica para el audio 16. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 16', russian: 'Полезная фраза 16', context: 'Contexto diario' },
        { spanish: 'Expresión común 16', russian: 'Обычное выражение 16', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: true, writing: false },
    },
    audioUrl: '/audio/c1-36.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 34,
    order: 36,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-37',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 17',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 17',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 17', russian: 'Пример 17' },
          { spanish: 'Frase práctica 17', russian: 'Практическая фраза 17' },
          { spanish: 'Contexto real 17', russian: 'Реальный контекст 17' },
          { spanish: 'Aplicación 17', russian: 'Применение 17' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-37.mp3',
        transcript: 'Este es el texto de práctica para el audio 17. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 17', russian: 'Полезная фраза 17', context: 'Contexto diario' },
        { spanish: 'Expresión común 17', russian: 'Обычное выражение 17', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: false, writing: false },
    },
    audioUrl: '/audio/c1-37.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 35,
    order: 37,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-38',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 18',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 18',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 18', russian: 'Пример 18' },
          { spanish: 'Frase práctica 18', russian: 'Практическая фраза 18' },
          { spanish: 'Contexto real 18', russian: 'Реальный контекст 18' },
          { spanish: 'Aplicación 18', russian: 'Применение 18' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-38.mp3',
        transcript: 'Este es el texto de práctica para el audio 18. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 18', russian: 'Полезная фраза 18', context: 'Contexto diario' },
        { spanish: 'Expresión común 18', russian: 'Обычное выражение 18', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: true, writing: true },
    },
    audioUrl: '/audio/c1-38.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 36,
    order: 38,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-39',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 19',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 19',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 19', russian: 'Пример 19' },
          { spanish: 'Frase práctica 19', russian: 'Практическая фраза 19' },
          { spanish: 'Contexto real 19', russian: 'Реальный контекст 19' },
          { spanish: 'Aplicación 19', russian: 'Применение 19' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-39.mp3',
        transcript: 'Este es el texto de práctica para el audio 19. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 19', russian: 'Полезная фраза 19', context: 'Contexto diario' },
        { spanish: 'Expresión común 19', russian: 'Обычное выражение 19', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: false, writing: false },
    },
    audioUrl: '/audio/c1-39.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 37,
    order: 39,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },  {
    id: 'c1-40',
    levelId: 'c1',
    title: 'Futuro Perfecto - Урок 20',
    description: 'Практика и углубленное изучение темы',
    content: {
      introduction: {
        title: 'Futuro Perfecto - Часть 20',
        goals: ['Освоить тему', 'Практиковать в контексте', 'Изб егать ошибок', 'Улучшить понимание'],
        overview: 'Детальное изучение темы с практическими примерами',
      },
      newWords: [],
      grammar: {
        title: 'Грамматика: Futuro Perfecto',
        explanation: 'Подробное объяснение грамматической структуры',
        examples: [
          { spanish: 'Ejemplo 20', russian: 'Пример 20' },
          { spanish: 'Frase práctica 20', russian: 'Практическая фраза 20' },
          { spanish: 'Contexto real 20', russian: 'Реальный контекст 20' },
          { spanish: 'Aplicación 20', russian: 'Применение 20' },
        ],
      },
      listening: {
        audioUrl: '/audio/c1-40.mp3',
        transcript: 'Este es el texto de práctica para el audio 20. Escucha atentamente y trata de entender el contexto. La práctica regular es esencial para el progreso.',
        questions: [
          { question: '¿Cuál es el tema principal?', options: ['tema A', 'tema B', 'Futuro Perfecto', 'tema D'], correctAnswer: 2 },
          { question: '¿Qué se recomienda?', options: ['no practicar', 'practicar regularmente', 'olvidar', 'ignorar'], correctAnswer: 1 },
        ],
      },
      phrases: [
        { spanish: 'Frase útil 20', russian: 'Полезная фраза 20', context: 'Contexto diario' },
        { spanish: 'Expresión común 20', russian: 'Обычное выражение 20', context: 'Uso formal' },
      ],
      homework: { vocabularyTest: true, listening: true, reading: true, writing: false },
    },
    audioUrl: '/audio/c1-40.mp3',
    readingText: 'Texto de lectura para Futuro Perfecto. Este material te ayuda a comprender mejor la estructura y uso de esta construcción gramatical. La práctica constante y la exposición al idioma son claves para el dominio del español avanzado.',
    duration: 28,
    order: 40,
    isFree: false,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
]
